import type { OpenAPIObject, SchemaObject, ReferenceObject } from 'openapi3-ts/oas31';

type SchemaDict = Record<string, SchemaObject | ReferenceObject>;
type SchemaProperties = SchemaDict;
type SchemaItems = SchemaObject | ReferenceObject;
type CombinatorArray = (SchemaObject | ReferenceObject)[];

export function decorateCanonicalUrls(schema: OpenAPIObject): OpenAPIObject {
  const clone = structuredClone(schema);

  if (!clone.components?.schemas) {
    return clone;
  }

  const entries = Object.entries(clone.components.schemas);
  for (const [schemaName, schemaDef] of entries) {
    if (!schemaName.includes('Response') && !schemaName.includes('Schema')) {
      continue;
    }
    const decorated = decorateSchema(schemaDef);
    if (!isReferenceObject(decorated)) {
      clone.components.schemas[schemaName] = decorated;
    }
  }

  return clone;
}

function isReferenceObject(value: unknown): value is ReferenceObject {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    return false;
  }
  if (!Object.hasOwn(value, '$ref')) {
    return false;
  }
  const descriptor = Object.getOwnPropertyDescriptor(value, '$ref');
  return typeof descriptor?.value === 'string';
}

function decorateSchema(schema: SchemaObject | ReferenceObject): SchemaObject | ReferenceObject {
  if (isReferenceObject(schema)) {
    return schema;
  }

  const working: SchemaObject = schema;

  if (hasPropertiesField(working)) {
    return decorateObjectWithCanonicalUrl(working);
  }

  if (isArraySchemaWithItems(working)) {
    return decorateArrayItems(working);
  }

  if (hasAnyOf(working)) {
    return decorateWithCombinator(working, 'anyOf');
  }
  if (hasOneOf(working)) {
    return decorateWithCombinator(working, 'oneOf');
  }
  if (hasAllOf(working)) {
    return decorateWithCombinator(working, 'allOf');
  }

  return working;
}

function hasPropertiesField(
  schema: SchemaObject,
): schema is SchemaObject & { properties: SchemaProperties } {
  return (
    schema.type === 'object' &&
    'properties' in schema &&
    schema.properties !== undefined &&
    typeof schema.properties === 'object'
  );
}

function isArraySchemaWithItems(
  schema: SchemaObject,
): schema is SchemaObject & { items: SchemaItems } {
  if (schema.type !== 'array') {
    return false;
  }
  if (!('items' in schema)) {
    return false;
  }
  const items = schema.items;
  if (!items || typeof items !== 'object') {
    return false;
  }
  if (Array.isArray(items)) {
    return false;
  }
  return true;
}

function hasAnyOf(schema: SchemaObject): schema is SchemaObject & { anyOf: CombinatorArray } {
  return Array.isArray(schema.anyOf);
}

function hasOneOf(schema: SchemaObject): schema is SchemaObject & { oneOf: CombinatorArray } {
  return Array.isArray(schema.oneOf);
}

function hasAllOf(schema: SchemaObject): schema is SchemaObject & { allOf: CombinatorArray } {
  return Array.isArray(schema.allOf);
}

function decorateObjectWithCanonicalUrl(
  schema: SchemaObject & { properties: SchemaProperties },
): SchemaObject {
  const canonical: SchemaObject = {
    type: 'string',
    description: 'The canonical URL for this resource, generated by the SDK',
    example: 'https://www.thenational.academy/teachers/lessons/example-lesson',
  };
  const nextProps: SchemaProperties = { ...schema.properties, canonicalUrl: canonical };
  schema.properties = nextProps;
  return schema;
}

function decorateArrayItems(schema: SchemaObject & { items: SchemaItems }): SchemaObject {
  const decoratedItems = decorateSchema(schema.items);
  return { ...schema, items: decoratedItems };
}

function decorateWithCombinator(
  schema: SchemaObject,
  key: 'anyOf' | 'oneOf' | 'allOf',
): SchemaObject {
  if (key === 'anyOf' && Array.isArray(schema.anyOf)) {
    schema.anyOf = schema.anyOf.map(decorateSchema);
    return schema;
  }
  if (key === 'oneOf' && Array.isArray(schema.oneOf)) {
    schema.oneOf = schema.oneOf.map(decorateSchema);
    return schema;
  }
  if (key === 'allOf' && Array.isArray(schema.allOf)) {
    schema.allOf = schema.allOf.map(decorateSchema);
    return schema;
  }
  return schema;
}
