/**
 * Unit tests for schema separation functionality
 * Following TDD approach - tests written before implementation
 */

import { describe, it, expect } from 'vitest';
import type { OpenAPIObject } from 'openapi3-ts/oas31';

import { createOpenCurriculumSchema } from './schema-separation-core.js';
import { schemaWithNestedResponses } from './test-fixtures.js';

describe('schema separation', () => {
  describe('createOpenCurriculumSchema', () => {
    it('returns original clone and decorated SDK schema without mutating the input', () => {
      const validatedSchema: OpenAPIObject = {
        openapi: '3.0.3',
        info: { title: 'Oak OpenAPI', version: '1.0.0' },
        paths: {},
        components: {
          schemas: {
            LessonResponse: {
              type: 'object',
              properties: {
                title: { type: 'string' },
              },
            },
          },
        },
      };

      const { original, sdk } = createOpenCurriculumSchema(validatedSchema);

      expect(original).toEqual(validatedSchema);
      expect(original).not.toBe(validatedSchema);

      const lessonResponse = sdk.components?.schemas?.LessonResponse as Record<string, unknown>;
      const properties = lessonResponse.properties as Record<string, unknown>;
      expect(properties).toHaveProperty('canonicalUrl');
      expect(properties.canonicalUrl).toHaveProperty('type', 'string');

      const originalLesson = original.components?.schemas?.LessonResponse as Record<
        string,
        unknown
      >;
      const originalProperties = originalLesson.properties as Record<string, unknown>;
      expect(originalProperties).not.toHaveProperty('canonicalUrl');
    });

    it('preserves all original schema fields while adding canonicalUrl', () => {
      const validatedSchema: OpenAPIObject = {
        openapi: '3.0.3',
        info: { title: 'Oak OpenAPI', version: '1.0.0' },
        paths: {},
        components: {
          schemas: {
            LessonResponse: {
              type: 'object',
              properties: {
                title: { type: 'string' },
                description: { type: 'string' },
              },
            },
          },
        },
      };

      const { original, sdk } = createOpenCurriculumSchema(validatedSchema);

      const lessonResponse = sdk.components?.schemas?.LessonResponse as Record<string, unknown>;
      const properties = lessonResponse.properties as Record<string, unknown>;
      expect(properties.title).toEqual({ type: 'string' });
      expect(properties.description).toEqual({ type: 'string' });
      expect(properties.canonicalUrl).toEqual({
        type: 'string',
        description: 'The canonical URL for this resource, generated by the SDK',
        example: 'https://www.thenational.academy/teachers/lessons/example-lesson',
      });

      const originalLesson = original.components?.schemas?.LessonResponse as Record<
        string,
        unknown
      >;
      const originalProperties = originalLesson.properties as Record<string, unknown>;
      expect(originalProperties).not.toHaveProperty('canonicalUrl');
    });

    it('should add canonicalUrl to nested response schemas without mutating input', () => {
      const { original, sdk } = createOpenCurriculumSchema(schemaWithNestedResponses);

      const originalLesson = original.components?.schemas?.LessonResponse;
      const sdkLesson = sdk.components?.schemas?.LessonResponse;

      if (!originalLesson || !sdkLesson || !('properties' in sdkLesson)) {
        throw new Error('LessonResponse schema not present');
      }

      const originalProps = (originalLesson as { properties?: Record<string, unknown> }).properties;
      const sdkProps = (sdkLesson as { properties?: Record<string, unknown> }).properties;
      expect(originalProps?.canonicalUrl).toBeUndefined();
      expect(sdkProps?.canonicalUrl).toEqual({
        type: 'string',
        description: 'The canonical URL for this resource, generated by the SDK',
        example: 'https://www.thenational.academy/teachers/lessons/example-lesson',
      });

      const searchResponse = sdk.components?.schemas?.SearchResponse;
      expect(searchResponse && 'properties' in searchResponse).toBe(true);
      if (!searchResponse || !('properties' in searchResponse)) {
        throw new Error('SearchResponse schema not present');
      }

      const summary = (searchResponse as { properties: Record<string, unknown> }).properties
        .summary as { anyOf?: unknown };
      if (!Array.isArray(summary?.anyOf)) {
        throw new Error('SearchResponse.summary.anyOf missing');
      }
      expect(summary.anyOf).toHaveLength(2);
    });
  });
});
