import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    // ========================================================================
    // Root-level entry points
    // ========================================================================
    'src/index.ts',
    'src/elasticsearch.ts',
    'src/response-augmentation.ts',
    'src/response-augmentation-helpers.ts',

    // ========================================================================
    // Client entry points
    // ========================================================================
    'src/client/index.ts',
    'src/client/oak-base-client.ts',
    'src/client/middleware/index.ts',
    'src/client/middleware/auth.ts',
    'src/client/middleware/rate-limit.ts',
    'src/client/middleware/rate-limit-tracker.ts',
    'src/client/middleware/retry.ts',
    'src/client/middleware/response-augmentation.ts',

    // ========================================================================
    // Config entry points
    // ========================================================================
    'src/config/index.ts',
    'src/config/rate-limit-config.ts',
    'src/config/retry-config.ts',

    // ========================================================================
    // Types entry points
    // ========================================================================
    'src/types/index.ts',
    'src/types/es-types.ts',
    'src/types/doc-bridges.ts',
    'src/types/public-types.ts',
    'src/types/openapi.ts',
    'src/types/response-augmentation.ts',
    'src/types/search-response-guards.ts',
    'src/types/generated/api-schema/api-paths-types.ts',
    'src/types/generated/api-schema/api-schema-base.ts',
    'src/types/generated/api-schema/path-parameters.ts',
    'src/types/generated/api-schema/path-utils.ts',
    'src/types/generated/api-schema/validation/request-parameter-map.ts',
    'src/types/generated/api-schema/response-map.ts',
    'src/types/generated/api-schema/routing/url-helpers.ts',
    'src/types/generated/api-schema/error-types/sdk-error-types.ts',
    'src/types/generated/api-schema/mcp-tools/contract/tool-descriptor.contract.ts',
    'src/types/generated/api-schema/mcp-tools/index.ts',
    'src/types/generated/api-schema/mcp-tools/generated/data/definitions.ts',
    'src/types/generated/api-schema/mcp-tools/generated/data/scopes-supported.ts',
    'src/types/generated/api-schema/mcp-tools/generated/data/index.ts',
    'src/types/generated/api-schema/mcp-tools/generated/data/tools/*.ts',
    'src/types/generated/api-schema/mcp-tools/generated/aliases/types.ts',
    'src/types/generated/api-schema/mcp-tools/generated/runtime/index.ts',
    'src/types/generated/api-schema/mcp-tools/generated/runtime/execute.ts',
    'src/types/generated/api-schema/mcp-tools/generated/stubs/index.ts',
    'src/types/generated/api-schema/mcp-tools/generated/stubs/tools/*.ts',
    'src/types/helpers/type-helpers.ts',
    'src/public/mcp-tools.ts',
    'src/public/search.ts',
    'src/public/bulk.ts',
    // Bulk parsing entry points
    'src/bulk/index.ts',
    'src/bulk/reader.ts',
    'src/bulk/processing.ts',
    // Generated bulk schemas (schema-first)
    'src/types/generated/bulk/index.ts',
    'src/types/generated/bulk/bulk-schemas.ts',
    // Bulk extractors
    'src/bulk/extractors/index.ts',
    'src/bulk/extractors/keyword-extractor.ts',
    'src/bulk/extractors/misconception-extractor.ts',
    'src/bulk/extractors/learning-point-extractor.ts',
    'src/bulk/extractors/teacher-tip-extractor.ts',
    'src/bulk/extractors/thread-extractor.ts',
    'src/bulk/extractors/prior-knowledge-extractor.ts',
    'src/bulk/extractors/nc-statement-extractor.ts',
    'src/bulk/extractors/pupil-outcome-extractor.ts',
    'src/bulk/extractors/content-guidance-extractor.ts',
    'src/bulk/extractors/transcript-extractor.ts',
    'src/bulk/extractors/supervision-level-extractor.ts',
    'src/bulk/extractors/why-this-why-now-extractor.ts',
    'src/bulk/extractors/unit-description-extractor.ts',
    'src/bulk/extractors/unit-lesson-extractor.ts',
    'src/bulk/extractors/year-phase-extractor.ts',
    // Bulk generators
    'src/bulk/generators/index.ts',
    'src/bulk/generators/analysis-report-generator.ts',
    'src/bulk/generators/misconception-graph-generator.ts',
    'src/bulk/generators/nc-coverage-generator.ts',
    'src/bulk/generators/prerequisite-graph-generator.ts',
    'src/bulk/generators/synonym-miner.ts',
    'src/bulk/generators/thread-progression-generator.ts',
    'src/bulk/generators/vocabulary-graph-generator.ts',
    'src/bulk/generators/write-graph-file.ts',
    'src/types/generated/search/index.ts',
    'src/types/generated/search/index-documents.ts',
    'src/types/generated/search/fixtures.ts',
    'src/types/generated/search/natural-requests.ts',
    'src/types/generated/search/parsed-query.ts',
    'src/types/generated/search/requests.ts',
    'src/types/generated/search/responses.lessons.ts',
    'src/types/generated/search/responses.units.ts',
    'src/types/generated/search/responses.sequences.ts',
    'src/types/generated/search/responses.multi.ts',
    'src/types/generated/search/scopes.ts',
    'src/types/generated/search/suggestions.ts',
    'src/types/generated/search/facets.ts',
    // ES mappings (generated from field definitions)
    'src/types/generated/search/es-mappings/index.ts',
    'src/types/generated/search/es-mappings/oak-lessons.ts',
    'src/types/generated/search/es-mappings/oak-units.ts',
    'src/types/generated/search/es-mappings/oak-unit-rollup.ts',
    'src/types/generated/search/es-mappings/oak-sequences.ts',
    'src/types/generated/search/es-mappings/oak-sequence-facets.ts',
    'src/types/generated/search/es-mappings/oak-meta.ts',
    'src/types/generated/search/es-mappings/oak-zero-hit-telemetry.ts',
    'src/types/generated/search/es-mappings/oak-threads.ts',
    'src/types/generated/search/es-mappings/oak-curriculum-glossary.ts',
    'src/types/generated/search/es-mappings/oak-ref-key-stages.ts',
    'src/types/generated/search/es-mappings/oak-ref-subjects.ts',
    'src/types/generated/query-parser/index.ts',
    'src/types/generated/widget-constants.ts',
    'src/types/generated/observability/index.ts',
    'src/types/generated/observability/zero-hit-fixtures.ts',
    'src/types/generated/admin/index.ts',
    'src/types/generated/admin/stream-fixtures.ts',
    'src/types/generated/zod/search/index.ts',
    'src/types/generated/zod/search/output/index.ts',
    'src/types/generated/zod/search/output/sequence-facets.ts',
    'src/types/generated/zod/curriculumZodSchemas.ts',
    'src/validation/index.ts',
    'src/validation/request-validators.ts',
    'src/validation/curriculum-response-validators.ts',
    'src/validation/search-response-validators.ts',
    'src/validation/types.ts',
    // MCP entry points
    'src/mcp/execute-tool-call.ts',
    'src/mcp/zod-input-schema.ts',
    'src/mcp/universal-tool-shared.ts',
    'src/mcp/aggregated-search/index.ts',
    'src/mcp/aggregated-search/tool-definition.ts',
    'src/mcp/aggregated-search/types.ts',
    'src/mcp/aggregated-search/validation.ts',
    'src/mcp/aggregated-search/execution.ts',
    'src/mcp/aggregated-fetch.ts',
    'src/mcp/aggregated-ontology.ts',
    'src/mcp/aggregated-knowledge-graph.ts',
    'src/mcp/aggregated-help/index.ts',
    'src/mcp/aggregated-help/definition.ts',
    'src/mcp/aggregated-help/help-content.ts',
    'src/mcp/aggregated-help/execution.ts',
    'src/mcp/ontology-data.ts',
    'src/mcp/knowledge-graph-data.ts',
    'src/mcp/knowledge-graph-resource.ts',
    'src/mcp/tool-guidance-types.ts',
    'src/mcp/tool-guidance-data.ts',
    'src/mcp/documentation-resources.ts',
    'src/mcp/mcp-prompts.ts',
    'src/mcp/ontology-resource.ts',
    'src/mcp/universal-tools/index.ts',
    'src/mcp/universal-tools/definitions.ts',
    'src/mcp/universal-tools/types.ts',
    'src/mcp/universal-tools/type-guards.ts',
    'src/mcp/universal-tools/zod-utils.ts',
    'src/mcp/universal-tools/list-tools.ts',
    'src/mcp/universal-tools/executor.ts',
    'src/mcp/stub-tool-executor.ts',
    'src/mcp/prerequisite-guidance.ts',
    'src/mcp/agent-support-tool-metadata.ts',
    'src/mcp/widget-constants.ts',
    'src/mcp/synonym-export.ts',
    // Synonym data files
    'src/mcp/synonyms/index.ts',
    'src/mcp/synonyms/computing.ts',
    'src/mcp/synonyms/maths.ts',
    'src/mcp/synonyms/music.ts',
    'src/mcp/synonyms/education.ts',
    'src/mcp/synonyms/geography.ts',
    'src/mcp/synonyms/history.ts',
    'src/mcp/synonyms/numbers.ts',
    'src/mcp/synonyms/english.ts',
    'src/mcp/synonyms/exam-boards.ts',
    'src/mcp/synonyms/subjects.ts',
    'src/mcp/synonyms/key-stages.ts',
    'src/mcp/synonyms/science.ts',
    // Prerequisite and thread progression tools
    'src/mcp/prerequisite-graph-data.ts',
    'src/mcp/aggregated-prerequisite-graph.ts',
    'src/mcp/thread-progression-data.ts',
    'src/mcp/aggregated-thread-progressions.ts',
  ],
  format: ['esm'],
  dts: false, // Let TypeScript handle declarations
  splitting: false,
  sourcemap: true,
  clean: true,
  target: 'node22',
  minify: false,
  bundle: false, // SDK should not bundle dependencies
  platform: 'neutral',
  external: [
    // Keep all dependencies external for SDK
    'zod',
  ],
  treeshake: true,
  tsconfig: './tsconfig.build.json',
  ignoreWatch: ['**/*.test.ts', '**/*.spec.ts'],
  outDir: 'dist',
  esbuildOptions(options) {
    options.plugins = options.plugins ?? [];
    options.plugins.push({
      name: 'ensure-js-extensions',
      setup(build) {
        build.onResolve({ filter: /^\./ }, (args) => {
          if (args.path.endsWith('.js') || args.path.endsWith('.json')) {
            return null;
          }
          return { path: `${args.path}.js` };
        });
      },
    });
  },
});
