import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/client/index.ts',
    'src/client/oak-base-client.ts',
    'src/client/middleware/index.ts',
    'src/client/middleware/auth.ts',
    'src/config/index.ts',
    'src/types/index.ts',
    'src/types/search-response-guards.ts',
    'src/types/generated/api-schema/api-paths-types.ts',
    'src/types/generated/api-schema/api-schema-base.ts',
    'src/types/generated/api-schema/path-parameters.ts',
    'src/types/generated/api-schema/path-utils.ts',
    'src/types/generated/api-schema/validation/request-parameter-map.ts',
    'src/types/generated/api-schema/response-map.ts',
    'src/types/generated/api-schema/routing/url-helpers.ts',
    'src/types/generated/api-schema/mcp-tools/contract/tool-descriptor.contract.ts',
    'src/types/generated/api-schema/mcp-tools/index.ts',
    'src/types/generated/api-schema/mcp-tools/generated/data/definitions.ts',
    'src/types/generated/api-schema/mcp-tools/generated/data/scopes-supported.ts',
    'src/types/generated/api-schema/mcp-tools/generated/data/index.ts',
    'src/types/generated/api-schema/mcp-tools/generated/data/tools/*.ts',
    'src/types/generated/api-schema/mcp-tools/generated/aliases/types.ts',
    'src/types/generated/api-schema/mcp-tools/generated/runtime/execute.ts',
    'src/types/generated/api-schema/mcp-tools/generated/runtime/lib.ts',
    'src/types/generated/api-schema/mcp-tools/generated/stubs/index.ts',
    'src/types/generated/api-schema/mcp-tools/generated/stubs/tools/*.ts',
    'src/types/helpers/type-helpers.ts',
    'src/public/mcp-tools.ts',
    'src/public/search.ts',
    'src/types/generated/search/index.ts',
    'src/types/generated/search/index-documents.ts',
    'src/types/generated/search/fixtures.ts',
    'src/types/generated/search/natural-requests.ts',
    'src/types/generated/search/parsed-query.ts',
    'src/types/generated/search/requests.ts',
    'src/types/generated/search/responses.lessons.ts',
    'src/types/generated/search/responses.units.ts',
    'src/types/generated/search/responses.sequences.ts',
    'src/types/generated/search/responses.multi.ts',
    'src/types/generated/search/scopes.ts',
    'src/types/generated/search/suggestions.ts',
    'src/types/generated/query-parser/index.ts',
    'src/types/generated/observability/index.ts',
    'src/types/generated/observability/zero-hit-fixtures.ts',
    'src/types/generated/admin/index.ts',
    'src/types/generated/admin/stream-fixtures.ts',
    'src/types/generated/zod/search/index.ts',
    'src/types/generated/zod/search/output/index.ts',
    'src/types/generated/zod/search/output/sequence-facets.ts',
    'src/types/generated/zod/curriculumZodSchemas.ts',
    'src/validation/index.ts',
    'src/validation/request-validators.ts',
    'src/validation/curriculum-response-validators.ts',
    'src/validation/search-response-validators.ts',
    'src/validation/types.ts',
    'src/response-augmentation.ts',
    'src/mcp/execute-tool-call.ts',
    'src/mcp/zod-input-schema.ts',
    'src/mcp/universal-tool-shared.ts',
    'src/mcp/aggregated-search/index.ts',
    'src/mcp/aggregated-search/tool-definition.ts',
    'src/mcp/aggregated-search/types.ts',
    'src/mcp/aggregated-search/validation.ts',
    'src/mcp/aggregated-search/execution.ts',
    'src/mcp/aggregated-fetch.ts',
    'src/mcp/aggregated-ontology.ts',
    'src/mcp/ontology-data.ts',
    'src/mcp/universal-tools.ts',
    'src/mcp/stub-tool-executor.ts',
  ],
  format: ['esm'],
  dts: false, // Let TypeScript handle declarations
  splitting: false,
  sourcemap: true,
  clean: true,
  target: 'node22',
  minify: false,
  bundle: false, // SDK should not bundle dependencies
  platform: 'neutral',
  external: [
    // Keep all dependencies external for SDK
    'zod',
  ],
  treeshake: true,
  tsconfig: './tsconfig.build.json',
  ignoreWatch: ['**/*.test.ts', '**/*.spec.ts'],
  outDir: 'dist',
  esbuildOptions(options) {
    options.plugins = options.plugins ?? [];
    options.plugins.push({
      name: 'ensure-js-extensions',
      setup(build) {
        build.onResolve({ filter: /^\./ }, (args) => {
          if (args.path.endsWith('.js') || args.path.endsWith('.json')) {
            return null;
          }
          return { path: `${args.path}.js` };
        });
      },
    });
  },
});
