/**
 * Widget HTML Provider
 *
 * Resolves and reads the built MCP App HTML bundle from disk. The widget
 * HTML is generated by Vite (`widget/vite.config.ts`) and placed at
 * `dist/oak-banner.html`. This module handles the path resolution for both
 * development (tsx from `src/`) and production (tsup bundle from `dist/src/`).
 */

import { readFileSync } from 'node:fs';
import { basename, dirname, resolve } from 'node:path';

/**
 * Resolves the package root from `import.meta.dirname`.
 *
 * The server entry always runs from a directory named `src/`:
 * - **Development** (tsx): `<pkg>/src/` — parent is the package root
 * - **Production** (tsup bundle): `<pkg>/dist/src/` — parent is `dist/`,
 *   grandparent is the package root
 *
 * We detect the production layout by checking whether the parent directory
 * is named `dist`.
 */
const parentDir = dirname(import.meta.dirname);
const pkgRoot = basename(parentDir) === 'dist' ? dirname(parentDir) : parentDir;

/**
 * Path to the built MCP App HTML bundle consumed by the production HTML
 * provider. Named `oak-banner.html` to match the widget page naming
 * convention introduced in the multi-page widget dev server.
 *
 * Always resolves to `<pkg>/dist/oak-banner.html` regardless of whether
 * the code runs from `src/` (dev) or `dist/src/` (production).
 */
const WIDGET_HTML_PATH = resolve(pkgRoot, 'dist', 'oak-banner.html');

/**
 * Reads the built MCP App HTML bundle from disk for production resource reads.
 *
 * The file is generated by the Vite build step and is a self-contained HTML
 * document with inlined JS and CSS.
 */
export function readBuiltWidgetHtml(): string {
  return readFileSync(WIDGET_HTML_PATH, 'utf-8');
}
