import { SEARCH_SCOPES, SEARCH_SCOPES_WITH_ALL, type SearchScope } from '../types/oak';

export const NARROW_SEARCH_SCOPES = [...SEARCH_SCOPES] as const;
export const ALL_SEARCH_SCOPES = [...SEARCH_SCOPES_WITH_ALL] as const;

export const MULTI_SCOPE = ALL_SEARCH_SCOPES[0];
export const DEFAULT_NARROW_SCOPE: SearchScope = NARROW_SEARCH_SCOPES[0];
const [LESSON_SCOPE_VALUE, UNIT_SCOPE_VALUE, SEQUENCE_SCOPE_VALUE] = NARROW_SEARCH_SCOPES;

export const LESSONS_SCOPE = LESSON_SCOPE_VALUE;
export const UNITS_SCOPE = UNIT_SCOPE_VALUE;
export const SEQUENCES_SCOPE = SEQUENCE_SCOPE_VALUE;
