/**
 * Aerial-themed identity word group.
 */
export const AERIAL_IDENTITY_WORD_GROUP = {
  group: 'aerial',
  adjectives: [
    'airy',
    'windward',
    'lofty',
    'clouded',
    'highland',
    'cirrus',
    'swift',
    'skyward',
    'zephyrous',
    'blustery',
    'feathered',
    'uplifted',
    'open',
    'soaring',
    'stormbound',
    'windswept',
    'tempestuous',
    'thermal',
    'floating',
    'stratospheric',
  ],
  verbs: [
    'wheeling',
    'rising',
    'hovering',
    'gusting',
    'spiralling',
    'floating',
    'sweeping',
    'darting',
    'kiting',
    'lifting',
    'streaming',
    'buffeting',
    'circling',
    'vaulting',
    'gliding',
    'flying',
    'winging',
    'whirling',
    'lofting',
    'swooping',
  ],
  nouns: [
    'cloud',
    'gale',
    'zephyr',
    'squall',
    'sky',
    'wing',
    'aerie',
    'thermal',
    'updraft',
    'current',
    'breeze',
    'gust',
    'feather',
    'plume',
    'kite',
    'horizon',
    'summit',
    'cliff',
    'airstream',
    'falcon',
  ],
} as const;
