/**
 * Celestial-themed identity word group.
 */
export const CELESTIAL_IDENTITY_WORD_GROUP = {
  group: 'celestial',
  adjectives: [
    'celestial',
    'cosmic',
    'stellar',
    'lunar',
    'solar',
    'ethereal',
    'nebulous',
    'galactic',
    'twilit',
    'dawnlit',
    'starlit',
    'moonlit',
    'sunlit',
    'gilded',
    'radiant',
    'luminous',
    'prismatic',
    'glittering',
    'iridescent',
    'opalescent',
  ],
  verbs: [
    'drifting',
    'orbiting',
    'soaring',
    'gliding',
    'ascending',
    'glowing',
    'illuminating',
    'eclipsing',
    'transiting',
    'waning',
    'waxing',
    'dancing',
    'weaving',
    'threading',
    'scattering',
    'cascading',
    'beaming',
    'shimmering',
    'twinkling',
    'glimmering',
  ],
  nouns: [
    'nebula',
    'comet',
    'quasar',
    'galaxy',
    'supernova',
    'asteroid',
    'meteor',
    'planet',
    'star',
    'moon',
    'sun',
    'eclipse',
    'satellite',
    'constellation',
    'orbit',
    'twilight',
    'dawn',
    'dusk',
    'aurora',
    'prism',
  ],
} as const;
