/**
 * Ember-themed identity word group.
 */
export const EMBER_IDENTITY_WORD_GROUP = {
  group: 'ember',
  adjectives: [
    'embered',
    'fiery',
    'molten',
    'coppery',
    'burnished',
    'incandescent',
    'torrid',
    'cindery',
    'ashen',
    'volcanic',
    'hearthlit',
    'flamebright',
    'smouldering',
    'charcoal',
    'igneous',
    'furnace',
    'scorched',
    'kilned',
    'sparking',
    'brazen',
  ],
  verbs: [
    'kindling',
    'blazing',
    'smouldering',
    'flaring',
    'sparking',
    'forging',
    'tempering',
    'glowing',
    'burning',
    'roasting',
    'charring',
    'crackling',
    'warming',
    'brazing',
    'searing',
    'igniting',
    'banking',
    'stoking',
    'firing',
    'melting',
  ],
  nouns: [
    'ember',
    'kiln',
    'forge',
    'flame',
    'cinder',
    'ash',
    'coal',
    'hearth',
    'furnace',
    'brazier',
    'volcano',
    'caldera',
    'magma',
    'lava',
    'spark',
    'bonfire',
    'anvil',
    'crucible',
    'bellows',
    'pyre',
  ],
} as const;
