/**
 * Botanical-themed identity word group.
 */
export const BOTANICAL_IDENTITY_WORD_GROUP = {
  group: 'botanical',
  adjectives: [
    'verdant',
    'lush',
    'mossy',
    'leafy',
    'ferny',
    'sylvan',
    'woodland',
    'arboreal',
    'evergreen',
    'deciduous',
    'fragrant',
    'dewy',
    'shaded',
    'wooded',
    'blooming',
    'fruited',
    'fronded',
    'gnarled',
    'twigged',
    'vining',
  ],
  verbs: [
    'growing',
    'sprouting',
    'blossoming',
    'branching',
    'flowering',
    'ripening',
    'swaying',
    'rustling',
    'whispering',
    'bending',
    'climbing',
    'twining',
    'creeping',
    'spreading',
    'sheltering',
    'shedding',
    'regrowing',
    'budding',
    'fruiting',
    'foraging',
  ],
  nouns: [
    'grove',
    'copse',
    'glade',
    'meadow',
    'thicket',
    'canopy',
    'sapling',
    'fern',
    'moss',
    'bark',
    'leaf',
    'branch',
    'root',
    'blossom',
    'petal',
    'stamen',
    'seed',
    'pollen',
    'dew',
    'forest',
  ],
} as const;
