/**
 * Nocturnal-themed identity word group.
 */
export const NOCTURNAL_IDENTITY_WORD_GROUP = {
  group: 'nocturnal',
  adjectives: [
    'shadowed',
    'dusky',
    'midnight',
    'umbral',
    'silvered',
    'veiled',
    'dim',
    'quiet',
    'moonless',
    'starless',
    'masked',
    'hidden',
    'penumbral',
    'velvet',
    'shaded',
    'lanternlit',
    'secret',
    'mistbound',
    'hushed',
    'eclipsed',
  ],
  verbs: [
    'stalking',
    'slipping',
    'vanishing',
    'masking',
    'cloaking',
    'hiding',
    'prowling',
    'lurking',
    'whispering',
    'creeping',
    'fading',
    'glimmering',
    'watching',
    'listening',
    'shrouding',
    'veiling',
    'dimming',
    'silencing',
    'stealing',
    'passing',
  ],
  nouns: [
    'shadow',
    'veil',
    'dusk',
    'night',
    'shade',
    'cloak',
    'lantern',
    'mask',
    'crescent',
    'silhouette',
    'hush',
    'wisp',
    'raven',
    'moth',
    'owl',
    'candle',
    'threshold',
    'mist',
    'mirror',
    'secret',
  ],
} as const;
