/**
 * Maritime-themed identity word group.
 */
export const MARITIME_IDENTITY_WORD_GROUP = {
  group: 'maritime',
  adjectives: [
    'oceanic',
    'tidal',
    'coastal',
    'briny',
    'deep',
    'abyssal',
    'pelagic',
    'salty',
    'foamy',
    'misty',
    'squally',
    'stormy',
    'glassy',
    'choppy',
    'pearly',
    'riverine',
    'lacustrine',
    'estuarine',
    'seaworthy',
    'breezy',
  ],
  verbs: [
    'sailing',
    'navigating',
    'charting',
    'plumbing',
    'fathoming',
    'surfing',
    'cresting',
    'rolling',
    'lapping',
    'washing',
    'ebbing',
    'flowing',
    'anchoring',
    'mooring',
    'berthing',
    'fishing',
    'diving',
    'snorkelling',
    'swimming',
    'drifting',
  ],
  nouns: [
    'harbour',
    'lighthouse',
    'anchor',
    'sail',
    'mast',
    'prow',
    'stern',
    'hull',
    'rudder',
    'compass',
    'sextant',
    'beacon',
    'jetty',
    'pier',
    'dock',
    'lagoon',
    'atoll',
    'reef',
    'archipelago',
    'fjord',
  ],
} as const;
