import {
  configs,
  appArchitectureRules,
  createImportResolverSettings,
  defineConfigArray,
  ignores as globalIgnores,
  testRules,
} from '@oaknational/eslint-plugin-standards';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';
import globals from 'globals';
import eslint from '@eslint/js';
import { importX } from 'eslint-plugin-import-x';
import tseslint from 'typescript-eslint';

const thisDir = dirname(fileURLToPath(import.meta.url));
const widgetDir = fileURLToPath(new URL('./widget', import.meta.url));
const workspaceImportResolverSettings = createImportResolverSettings({
  project: thisDir,
});
const widgetImportResolverSettings = createImportResolverSettings({
  project: widgetDir,
});
const javaScriptRuleOverrides = Object.fromEntries(
  configs.strict
    .flatMap((config) => Object.keys(config.rules ?? {}))
    .filter((ruleName) => ruleName.startsWith('@typescript-eslint/'))
    .map((ruleName) => [ruleName, 'off']),
);
// const wsTsProject = fileURLToPath(new URL('./tsconfig.lint.json', import.meta.url));

const config = defineConfigArray(
  {
    ignores: [
      ...globalIgnores,
      'dist/**',
      '*.log',
      '.turbo/**',
      '.widget-build/**',
      '.logs/**',
      'temp-secrets/**',
      '../../.agent/reference/**',
      // Build-time copies from the design packages (see
      // build-scripts/copy-oak-ds.ts). Generated, gitignored, and owned by
      // their packages — linting them here would report those packages'
      // style choices as this app's errors. ESLint 9 does not read
      // .gitignore, and `lint` has no build dependency, so without these the
      // verdict depends on whether a build ran first. The dot-prefixed glob
      // covers the copier's transient staging/retired dirs, which only a
      // crash strands.
      'public/oak-ds/**',
      'public/oak-assets/**',
      'public/.oak-*/**',
      // Baked landing-page artefacts (build-scripts/bake-landing-page.ts):
      // same generated-and-gitignored class as the copies above.
      '.generated/**',
    ],
  },
  configs.strict,
  {
    files: ['**/*.js', '**/*.mjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.node,
        ...globals.es2021,
      },
      parserOptions: {
        program: null,
        project: false,
        projectService: false,
      },
    },
    rules: {
      ...javaScriptRuleOverrides,
      ...tseslint.configs.disableTypeChecked.rules,
      ...eslint.configs.recommended.rules,
      ...importX.flatConfigs.recommended.rules,
    },
  },
  // no special ignores for vitest.e2e.config.ts; treat as config file below
  {
    files: ['**/*.ts', '**/*.d.mts'],
    languageOptions: {
      parserOptions: {
        projectService: true,
        // project: wsTsProject,
        tsconfigRootDir: thisDir,
        // Allow files not explicitly included in the project to still be linted
        // allowDefaultProject: true,
      },
    },
    settings: workspaceImportResolverSettings,
    rules: {
      'import-x/no-relative-parent-imports': 'off',
      ...appArchitectureRules,
      'max-lines-per-function': ['error', { max: 50, skipComments: true, skipBlankLines: true }],
      // The baked-page specifier is an esbuild `text`-loader input
      // (src/app/landing-page-baked.ts), not a Node/TS-resolvable module:
      // the artefact is generated by the build and gitignored, and `lint`
      // carries no build edge, so resolving it here would make the verdict
      // depend on whether a build ran first (the class the ignores block
      // above documents). Existence is guaranteed by the build — the bake
      // runs before the bundle in esbuild.config.ts, and the bundle guard
      // assertBundleCarriesBakedLandingPage fails the build if the inline
      // regresses.
      'import-x/no-unresolved': [
        'error',
        { ignore: [String.raw`\.generated/landing-page\.html$`] },
      ],
    },
  },
  {
    // The landing page is server-rendered React under src/. Mirrors the
    // widget's typed-linting block; kept separate from the `**/*.ts` block
    // above because `ecmaFeatures.jsx` changes how `<T>x` parses in .ts.
    files: ['src/**/*.tsx'],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: thisDir,
        ecmaFeatures: { jsx: true },
      },
    },
    settings: workspaceImportResolverSettings,
    rules: {
      'import-x/no-relative-parent-imports': 'off',
      ...appArchitectureRules,
      'max-lines-per-function': ['error', { max: 50, skipComments: true, skipBlankLines: true }],
    },
  },
  // The estate's React tier (react-hooks rules-of-hooks/exhaustive-deps,
  // jsx-key, no-array-index-key, …) — files-scoped because configs.react
  // itself carries no `files` and rules-of-hooks must not bind plain .ts
  // helpers named use*. Scoped to product tsx ahead of the client-entry
  // and hooks work this page's stack lands next.
  ...configs.react.map((reactConfig) => ({ ...reactConfig, files: ['src/**/*.tsx'] })),
  {
    files: ['src/**/*.test.tsx', 'src/**/*.spec.tsx'],
    rules: {
      ...testRules,
      'import-x/no-relative-parent-imports': 'off',
      'import-x/no-restricted-paths': 'off',
      'max-lines-per-function': ['error', { max: 220, skipComments: true, skipBlankLines: true }],
    },
  },
  // ADR-162 observability-first: require structured emission in newly
  // exported async functions. Rule is path-scoped internally to apps/**
  // and packages/sdks/**.
  {
    files: ['src/**/*.ts', 'src/**/*.tsx'],
    rules: {
      '@oaknational/require-observability-emission': 'error',
    },
  },
  // ADR-088 Result pattern + ADR-162 engineering-axis: preserve caught
  // error context when throwing new errors inside catch blocks.
  //  Enforcement surface matches the observability emitter
  // surface because both are the same trust-boundary class — apps +
  // SDK runtime entry points; packages/core/* and packages/libs/* are
  // leaf layers whose error ergonomics differ. ESLint built-in rule
  // (added in 9.35.0) supersedes the originally planned custom
  // `require-error-cause` rule — the built-in is a documented superset
  // covering missing cause, cause-mismatch, destructured loss, and
  // variable shadowing. `requireCatchParameter: true` forbids no-param
  // catch blocks so every caught error is available as a cause.
  // See ADR-162 History 2026-04-19 addendum for the re-scoping
  // rationale and the opt-out protocol.
  {
    files: ['src/**/*.ts', 'src/**/*.tsx'],
    rules: {
      'preserve-caught-error': ['error', { requireCatchParameter: true }],
    },
  },
  {
    files: ['operations/**/*.ts'],
    rules: {
      'no-console': 'error',
    },
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    // TODO: remove once config DI standardisation is complete (see .agent/plans/architecture/config-architecture-standardisation-plan.md)
    ignores: [
      '**/*.test.ts',
      '**/*.spec.ts',
      // The .tsx test ignores are load-bearing, not symmetry: the
      // src/**/*.test.tsx testRules block precedes this one, so without
      // them this block's production no-restricted-syntax value would
      // override testRules for test .tsx files.
      '**/*.test.tsx',
      '**/*.spec.tsx',
      'operations/**',
      'e2e-tests/**',
      // Runtime composition root for Vercel's request handler import
      // contract. Like `src/index.ts`, this boundary legitimately
      // reads `process.env` once, then passes typed runtime config
      // into the app factory so the rest of the codebase stays under
      // env-library / DI policy.
      'src/server.ts',
      'src/index.ts',
      // Esbuild composition root invoked by Vercel Build Command via
      // `tsx`. process.env is the legitimate boundary-crossing read
      // (Vercel injects build env); the typed factories it calls
      // (`createSentryBuildPlugin`, `createMcpEsbuildOptions`) take
      // env as a parameter so all policy logic stays test-driven.
      // See ADR-163 §6 (amended by §L-8 WS3.1) and the file's module
      // TSDoc for the rationale.
      'esbuild.config.ts',
      // Repo-owned pre-preview build gate: reads process.env once, seeds
      // representative Vercel defaults, then shells into esbuild.config.ts.
      // The rest of the gate logic stays in pure helpers under
      // build-scripts/sentry-configured-build-gate.ts.
      'build-scripts/run-sentry-configured-build.ts',
      // Workspace tooling scripts (dev/test harness CLIs, e.g.
      // `run-requests.ts`, `server-harness.ts`, `embed-widget-html.ts`).
      // These are not product code — they read env vars at startup as
      // their composition contract. ADR-168 covers the all-TS-scripts
      // workspace rule and the runtime-only-scripts directory exception.
      'scripts/**/*.ts',
    ],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector:
            'MemberExpression[object.property.name="process"][property.name="env"], MemberExpression[object.name="process"][property.name="env"]',
          message:
            'Avoid using process.env directly. In product code use the runtime config provided by the env library instead. In test code pass simple values directly via DI.',
        },
        // MCP-187: the widget URI carries a per-build cache-busting hash
        // generated at sdk-codegen time. A hand-frozen `ui://widget/`
        // literal silently stops matching the generated value on deployed
        // builds — the widget then advertises but never registers (the
        // served-surface key froze exactly this way). Import WIDGET_URI
        // from `@oaknational/curriculum-sdk/public/mcp-tools.js` instead.
        // Test files are exempt via this block's ignores (fake widget URIs
        // are legitimate fixtures there).
        // esquery regex delimiters are `/`, so the URI's own slashes MUST use
        // the backslash-u002F escape form — a plain-slash pattern silently truncates
        // and the rule stops firing (negative-control-verified both ways).
        {
          selector: String.raw`Literal[value=/ui:\u002F\u002Fwidget\u002F/]`,
          message:
            'Hand-frozen widget URI literal: the widget URI is generated per build (MCP-187). Import WIDGET_URI from @oaknational/curriculum-sdk/public/mcp-tools.js.',
        },
        {
          selector: String.raw`TemplateElement[value.raw=/ui:\u002F\u002Fwidget\u002F/]`,
          message:
            'Hand-frozen widget URI in a template literal: the widget URI is generated per build (MCP-187). Import WIDGET_URI from @oaknational/curriculum-sdk/public/mcp-tools.js.',
        },
      ],
    },
  },
  {
    files: ['widget/**/*.ts', 'widget/**/*.tsx'],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: thisDir,
        ecmaFeatures: { jsx: true },
      },
    },
    settings: widgetImportResolverSettings,
    rules: {
      'import-x/no-relative-parent-imports': 'off',
      ...appArchitectureRules,
      'max-lines-per-function': ['error', { max: 50, skipComments: true, skipBlankLines: true }],
    },
  },
  {
    files: ['widget/**/*.test.tsx', 'widget/**/*.test.ts'],
    rules: {
      ...testRules,
      'import-x/no-relative-parent-imports': 'off',
      'import-x/no-restricted-paths': 'off',
      'max-lines-per-function': ['error', { max: 220, skipComments: true, skipBlankLines: true }],
    },
  },
  {
    files: ['**/*.test.ts', '**/*.spec.ts'],
    rules: {
      ...testRules,
      'import-x/no-relative-parent-imports': 'off',
      'import-x/no-restricted-paths': 'off',
      'max-lines-per-function': ['error', { max: 220, skipComments: true, skipBlankLines: true }],
    },
  },
  {
    files: ['e2e-tests/**/*.test.ts'],
    rules: {
      'max-lines-per-function': ['error', { max: 300, skipComments: true, skipBlankLines: true }],
    },
  },
  {
    // Test-ceremony migration backlog (per
    // `.agent/plans/architecture-and-infrastructure/current/test-ceremony-production-factory-audit.plan.md`).
    // Each file listed here is a known violation of the hermetic-test
    // boundary rules — either importing a production factory it does not
    // test (runtime-config / http-observability) or using vi.mock /
    // vi.stubGlobal / vi.doMock. Delete a line as each file migrates.
    // Flip to empty allowlist at plan WS5 close.
    files: [
      // production-factory imports (not subject under test)
      'src/oauth-proxy/oauth-proxy-routes.integration.test.ts',
      'src/handlers-observability.integration.test.ts',
      'src/app/setup-error-handlers.integration.test.ts',
      'src/app/oauth-and-caching-setup.unit.test.ts',
      'src/app/bootstrap-helpers.unit.test.ts',
      'src/handlers-mcp-span.integration.test.ts',
      'src/asset-download/asset-download-route.integration.test.ts',
      'src/check-mcp-client-auth.di.integration.test.ts',
      'src/tool-handler-with-auth.integration.test.ts',
      'src/handlers.integration.test.ts',
      // vi.mock family
      'src/auth/mcp-auth/mcp-auth-clerk.integration.test.ts',
      'src/correlation/middleware.integration.test.ts',
      'src/handlers-tool-registration.integration.test.ts',
      'src/observability/sentry-observability-delegates.unit.test.ts',
      'src/register-resources-observability.integration.test.ts',
    ],
    rules: {
      'no-restricted-properties': 'off',
    },
  },
  {
    files: ['build-scripts/**/*.ts'],
    rules: {
      'no-console': 'off',
    },
  },
  {
    // Esbuild composition root invoked by Vercel Build Command via `tsx`.
    // process.env is the legitimate boundary-crossing read (Vercel
    // injects build env), the typed factories `createSentryBuildPlugin`
    // and `createMcpEsbuildOptions` then take env as a parameter, and
    // console.* output is how Vercel's build log sees what the
    // composition root decided. See ADR-163 §6 (amended by §L-8 WS3.1)
    // and the file's module TSDoc.
    files: ['esbuild.config.ts'],
    rules: {
      'no-console': 'off',
    },
  },
  {
    // Workspace tooling scripts: dev/test harness CLIs (e.g.
    // `run-requests.ts`, `server-harness.ts`, `embed-widget-html.ts`).
    // These are tooling, not product code — they read env vars at
    // startup, structure heterogeneous log metadata via
    // `Record<string, unknown>`, and are organised as imperative
    // scripts rather than decomposed modules. The same architectural
    // class as `build-scripts/**/*.{js,mjs}` (already exempted below)
    // and the search-cli's `scripts/**/*.ts` block. ADR-168 records
    // the workspace-script tier.
    files: ['scripts/**/*.ts'],
    rules: {
      'no-console': 'off',
      complexity: 'off',
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      'max-statements': 'off',
      '@typescript-eslint/no-restricted-types': 'off',
    },
  },
  {
    files: ['operations/**/*.unit.test.ts', 'operations/**/*.integration.test.ts'],
    rules: {
      ...testRules,
      'import-x/no-relative-parent-imports': 'off',
      'import-x/no-restricted-paths': 'off',
      'max-lines-per-function': ['error', { max: 220, skipComments: true, skipBlankLines: true }],
    },
  },
  {
    files: ['build-scripts/**/*.js', 'build-scripts/**/*.mjs'],
    rules: {
      complexity: 'off',
      'import-x/no-relative-parent-imports': 'off',
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      'max-statements': 'off',
      'no-console': 'off',
    },
  },
  {
    // Dedicated no-compile-no-deps directory per ADR-168. These
    // scripts execute in environments that run BEFORE `pnpm install`
    // (e.g. Vercel's `ignoreCommand`), so they cannot have a build
    // step or external dependencies. They inline vendored helpers
    // (semver), read process.env directly as their composition
    // contract, and intentionally remain imperative single-file
    // scripts. Same architectural class as `build-scripts/**/*.{js,mjs}`.
    files: ['runtime-only-scripts/**/*.js', 'runtime-only-scripts/**/*.mjs'],
    rules: {
      complexity: 'off',
      'import-x/no-relative-parent-imports': 'off',
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      'max-statements': 'off',
      'no-console': 'off',
    },
  },
  {
    files: ['scripts/**/*.js', 'scripts/**/*.mjs'],
    rules: {
      complexity: 'off',
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      'max-statements': 'off',
      'no-console': 'off',
    },
  },
  {
    files: [
      '**/*.config.ts',
      'eslint.config.ts',
      'eslint.config.base.ts',
      'vitest.config.ts',
      'vitest.e2e.config.ts',
      'vitest.widget.config.ts',
    ],
    languageOptions: {
      parserOptions: {
        projectService: true,
        // project: './tsconfig.json',
        tsconfigRootDir: thisDir,
      },
    },
    rules: {
      '@typescript-eslint/await-thenable': 'off',
      '@typescript-eslint/no-array-delete': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      'import-x/no-relative-packages': 'off',
      'import-x/no-relative-parent-imports': 'off',
      'import-x/no-named-as-default-member': 'off',
      'max-lines-per-function': ['error', { max: 200, skipComments: true, skipBlankLines: true }],
      'max-lines': 'off',
      'no-restricted-properties': 'off',
    },
  },
  {
    // MCP-403: test HTTP servers must own the exact loopback address test
    // clients dial. Bare supertest boots host-less servers on `::` while
    // its client dials 127.0.0.1, so a foreign v4 listener on the same
    // ephemeral port silently receives the request under concurrent-graph
    // load. The loopback-request helper is the sanctioned entry point; a
    // host-less listen in a test is the same vulnerable shape spelled by
    // hand. The helper itself is not a test file, so these rules never
    // apply to it — no exemption needed.
    //
    // Flat-config rule values REPLACE rather than merge, so this block
    // re-carries the shared testRules values for both rules — dropping
    // them here would silently disable the ADR-078 hermetic-test bans
    // for the app's whole test surface.
    //
    // The listen selector flags any `.listen(...)` whose second argument
    // is not a literal: it catches listen(), listen(0), listen(0, cb),
    // and listen(0, undefined) — every shape that falls through to the
    // host-less `::` bind. Known conservative residuals: an explicit
    // listen(0, '::') passes (deliberate, not the silent default); an
    // options-object listen({ port, host }) is flagged even when
    // host-ful (esquery cannot discriminate — use the positional form);
    // a destructured bare `listen` and a dynamic import of supertest are
    // unreachable by these rules.
    files: ['**/*.test.ts', '**/*.test.tsx', '**/*.spec.ts', '**/*.spec.tsx'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            ...testRules['no-restricted-imports'][1].patterns,
            {
              group: ['supertest', 'supertest/*'],
              message:
                'Bare supertest boots host-less (`::`) servers whose ports foreign v4 listeners can share (MCP-403). Import { request } from the loopback-request test helper instead.',
            },
          ],
        },
      ],
      'no-restricted-syntax': [
        'error',
        ...testRules['no-restricted-syntax'].slice(1),
        {
          selector:
            'CallExpression[callee.property.name="listen"]:not([arguments.1.type="Literal"])',
          message:
            'A listen(...) without a literal host in a test binds `::` while test clients dial 127.0.0.1 (MCP-403). Pass an explicit host — listen(port, "127.0.0.1") or listen(port, "127.0.0.1", callback) — or use the loopback-request helper.',
        },
      ],
    },
  },
);

export default config;
