/**
 * GENERATED FILE - DO NOT EDIT
 *
 * This file is automatically generated from the Oak Curriculum API OpenAPI schema.
 * To regenerate, run: pnpm generate:types
 *
 * Last generated: 2025-08-10T11:40:46.695Z
 */

export interface TranscriptResponseSchema {
  transcript: string;
  vtt: string;
}

export interface LessonAssetsResponseSchema {
  attribution?: string[];
  assets?: {
    type: string;
    label: string;
    url: string;
  }[];
}

export interface SubjectResponseSchema {
  subjectTitle: string;
  subjectSlug: string;
  sequenceSlugs: {
    sequenceSlug: string;
    years: number[];
    keyStages: {
      keyStageTitle: string;
      keyStageSlug: string;
    }[];
    phaseSlug: string;
    phaseTitle: string;
    ks4Options: {
      title: string;
      slug: string;
    };
  }[];
  years: number[];
  keyStages: {
    keyStageTitle: string;
    keyStageSlug: string;
  }[];
}

export interface QuestionForLessonsResponseSchema {
  starterQuiz: unknown[];
  exitQuiz: unknown[];
}

export interface LessonSummaryResponseSchema {
  lessonTitle: string;
  unitSlug: string;
  unitTitle: string;
  subjectSlug: string;
  subjectTitle: string;
  keyStageSlug: string;
  keyStageTitle: string;
  lessonKeywords: {
    keyword: string;
    description: string;
  }[];
  keyLearningPoints: {
    keyLearningPoint: string;
  }[];
  misconceptionsAndCommonMistakes: {
    misconception: string;
    response: string;
  }[];
  pupilLessonOutcome?: string;
  teacherTips: {
    teacherTip: string;
  }[];
  contentGuidance: unknown;
  supervisionLevel: unknown;
  downloadsAvailable: boolean;
}

export interface UnitSummaryResponseSchema {
  unitSlug: string;
  unitTitle: string;
  yearSlug: string;
  year: unknown;
  phaseSlug: string;
  subjectSlug: string;
  keyStageSlug: string;
  notes?: string;
  description?: string;
  priorKnowledgeRequirements: string[];
  nationalCurriculumContent: string[];
  whyThisWhyNow?: string;
  threads?: {
    slug: string;
    title: string;
    order: number;
  }[];
  categories?: {
    categoryTitle: string;
    categorySlug?: string;
  }[];
  unitLessons: {
    lessonSlug: string;
    lessonTitle: string;
    lessonOrder?: number;
    state: string;
  }[];
}

export interface error_UNAUTHORIZED {
  message: string;
  code: string;
  issues?: {
    message: string;
  }[];
}

export interface error_FORBIDDEN {
  message: string;
  code: string;
  issues?: {
    message: string;
  }[];
}

export interface error_INTERNAL_SERVER_ERROR {
  message: string;
  code: string;
  issues?: {
    message: string;
  }[];
}

export interface RateLimitResponseSchema {
  limit: number;
  remaining: number;
  reset: number;
}
