/**
 * Emitted module content for the graph-corpus dataset (G1a + G2 + G4b).
 *
 * @remarks
 * The literal lines of the generated `types.ts` (re-exporting the
 * generator-owned types) that `write-json-graph-corpus-file.ts` writes
 * alongside `data.json`; the loader lines live in
 * `graph-corpus-emitted-index-lines.ts`.
 */

export const graphCorpusTypesModuleLines: readonly string[] = [
  '/**',
  ' * Type definitions for the graph corpus.',
  ' *',
  ' * @remarks',
  ' * Generated by the graph corpus JSON writer. The corpus types are defined',
  ' * once in the generator (the single source of truth) and re-exported here,',
  ' * so no hand-maintained type runs parallel to the generated corpus',
  ' * (Decision A / ADR-031).',
  ' */',
  '',
  'export type {',
  '  GraphCorpus,',
  '  GraphCorpusNode,',
  '  GraphCorpusUnitNode,',
  '  GraphCorpusThreadNode,',
  '  GraphCorpusLessonNode,',
  '  GraphCorpusMisconceptionNode,',
  '  GraphCorpusKeywordNode,',
  '  GraphCorpusEdge,',
  '  GraphCorpusEdgeType,',
  '  GraphCorpusNodeId,',
  '  GraphCorpusUnitNodeId,',
  '  GraphCorpusThreadNodeId,',
  '  GraphCorpusLessonNodeId,',
  '  GraphCorpusMisconceptionNodeId,',
  '  GraphCorpusKeywordNodeId,',
  '  GraphCorpusStats,',
  '  GraphCorpusNodeKindCounts,',
  '  GraphCorpusEdgeTypeCounts,',
  '  GraphCorpusDroppedEdge,',
  '  GraphCorpusDroppedDuplicate,',
  '  GraphCorpusSequence,',
  '  GraphCorpusSequencePlacement,',
  '  GraphCorpusUnitLessonRun,',
  "} from '../../../bulk/generators/graph-corpus-generator.js';",
  '',
];
