/**
 * Emitted JSON wire-shape declaration lines for the graph-corpus loader.
 *
 * @remarks
 * The literal lines declaring the raw `data.json` shapes (`Json*` interfaces)
 * inside the generated `index.ts`; the validating-loader lines that narrow
 * them into the generator-owned types live in
 * `graph-corpus-emitted-index-lines.ts`, which composes this block.
 */

export const graphCorpusJsonShapeLines: readonly string[] = [
  'interface JsonUnitNode {',
  "  readonly kind: 'unit';",
  '  readonly id: string;',
  '  readonly unitSlug: string;',
  '  readonly unitTitle: string;',
  '  readonly subject: string;',
  '  readonly keyStage: string;',
  '  readonly year?: number;',
  '  readonly priorKnowledge: readonly string[];',
  '  readonly threadSlugs: readonly string[];',
  '}',
  '',
  'interface JsonThreadNode {',
  "  readonly kind: 'thread';",
  '  readonly id: string;',
  '  readonly threadSlug: string;',
  '  readonly title: string;',
  '  readonly firstYear?: number;',
  '  readonly lastYear?: number;',
  '}',
  '',
  'interface JsonLessonNode {',
  "  readonly kind: 'lesson';",
  '  readonly id: string;',
  '  readonly lessonSlug: string;',
  '  readonly lessonTitle: string;',
  '  readonly subject: string;',
  '  readonly keyStage: string;',
  '}',
  '',
  'interface JsonMisconceptionNode {',
  "  readonly kind: 'misconception';",
  '  readonly id: string;',
  '  readonly misconception: string;',
  '  readonly response: string;',
  '}',
  '',
  'interface JsonKeywordNode {',
  "  readonly kind: 'keyword';",
  '  readonly id: string;',
  '  readonly term: string;',
  '  readonly description: string;',
  '  readonly frequency: number;',
  '  readonly firstYear: number;',
  '  readonly subjects: readonly string[];',
  '}',
  '',
  'type JsonGraphCorpusNode =',
  '  | JsonUnitNode',
  '  | JsonThreadNode',
  '  | JsonLessonNode',
  '  | JsonMisconceptionNode',
  '  | JsonKeywordNode;',
  '',
  'interface JsonGraphCorpusEdge {',
  '  readonly source: string;',
  '  readonly type: string;',
  '  readonly target: string;',
  '}',
  '',
  'interface JsonSequencePlacement {',
  '  readonly unitId: string;',
  '  readonly year?: number;',
  '}',
  '',
  'interface JsonSequence {',
  '  readonly threadId: string;',
  '  readonly subject: string;',
  '  readonly placements: readonly JsonSequencePlacement[];',
  '}',
  '',
  'interface JsonUnitLessonRun {',
  '  readonly unitId: string;',
  '  readonly lessonIds: readonly string[];',
  '}',
  '',
  'interface JsonGraphCorpus {',
  '  readonly version: string;',
  '  readonly generatedAt: string;',
  '  readonly sourceVersion: string;',
  '  readonly stats: GraphCorpusStats;',
  '  readonly nodes: readonly JsonGraphCorpusNode[];',
  '  readonly edges: readonly JsonGraphCorpusEdge[];',
  '  readonly sequences: readonly JsonSequence[];',
  '  readonly unitLessonRuns: readonly JsonUnitLessonRun[];',
  '  readonly droppedEdges: readonly GraphCorpusDroppedEdge[];',
  '  readonly droppedDuplicates: readonly GraphCorpusDroppedDuplicate[];',
  '  readonly seeAlso: string;',
  '}',
];
