/**
 * Misconception graph generator for the vocabulary mining pipeline.
 *
 * @remarks
 * Generates a graph of misconceptions extracted from curriculum lessons.
 * This graph helps teachers identify common mistakes and AI agents provide
 * targeted tutoring support.
 */
import type { ExtractedMisconception } from '../extractors/index.js';
import {
  serializeDatasetToJson,
  writeJsonDataset,
  type JsonDatasetDescriptor,
} from './write-json-dataset.js';

/**
 * A misconception node in the graph.
 */
export interface MisconceptionNode {
  /** The incorrect belief or common mistake */
  readonly misconception: string;
  /** How to address or correct the misconception */
  readonly response: string;
  /** Subject where this misconception appears */
  readonly subject: string;
  /** Key stage where this misconception is addressed */
  readonly keyStage: string;
  /** Lesson that addresses this misconception */
  readonly lessonSlug: string;
  /** Lesson title for context */
  readonly lessonTitle: string;
}

/**
 * Statistics about the misconception graph.
 */
export interface MisconceptionGraphStats {
  /** Total number of misconceptions */
  readonly totalMisconceptions: number;
  /** Count of misconceptions by subject */
  readonly bySubject: Readonly<Record<string, number>>;
  /** Count of misconceptions by key stage */
  readonly byKeyStage: Readonly<Record<string, number>>;
  /** List of subjects covered */
  readonly subjectsCovered: readonly string[];
}

/**
 * The complete misconception graph structure.
 */
export interface MisconceptionGraph {
  /** Semantic version of this graph */
  readonly version: string;
  /** When this graph was generated */
  readonly generatedAt: string;
  /** Source data version */
  readonly sourceVersion: string;
  /** Statistics about the graph */
  readonly stats: MisconceptionGraphStats;
  /** All misconception nodes */
  readonly nodes: readonly MisconceptionNode[];
  /** Cross-reference to related resources */
  readonly seeAlso: string;
}

/**
 * Calculates statistics from misconceptions.
 */
function calculateStats(
  misconceptions: readonly ExtractedMisconception[],
): MisconceptionGraphStats {
  const bySubject: Record<string, number> = {};
  const byKeyStage: Record<string, number> = {};
  const subjects = new Set<string>();

  for (const m of misconceptions) {
    bySubject[m.subject] = (bySubject[m.subject] ?? 0) + 1;
    byKeyStage[m.keyStage] = (byKeyStage[m.keyStage] ?? 0) + 1;
    subjects.add(m.subject);
  }

  return {
    totalMisconceptions: misconceptions.length,
    bySubject,
    byKeyStage,
    subjectsCovered: [...subjects].sort(),
  };
}

/**
 * Converts extracted misconceptions to graph nodes.
 */
function toNodes(misconceptions: readonly ExtractedMisconception[]): readonly MisconceptionNode[] {
  return misconceptions.map((m) => ({
    misconception: m.misconception,
    response: m.response,
    subject: m.subject,
    keyStage: m.keyStage,
    lessonSlug: m.lessonSlug,
    lessonTitle: m.lessonTitle,
  }));
}

/**
 * Generates misconception graph data from extracted misconceptions.
 *
 * @param misconceptions - Array of extracted misconceptions
 * @param sourceVersion - Version of the source bulk data
 * @returns MisconceptionGraph with all misconceptions and statistics
 *
 * @example
 * ```ts
 * const graph = generateMisconceptionGraphData(extractedData.misconceptions, '2025-12-26');
 * console.log(`Found ${graph.stats.totalMisconceptions} misconceptions`);
 * ```
 */
export function generateMisconceptionGraphData(
  misconceptions: readonly ExtractedMisconception[],
  sourceVersion: string,
): MisconceptionGraph {
  return {
    version: '1.0.0',
    generatedAt: new Date().toISOString(),
    sourceVersion,
    stats: calculateStats(misconceptions),
    nodes: toNodes(misconceptions),
    seeAlso: 'Use get-curriculum-model for complete orientation including curriculum structure',
  };
}

/**
 * Misconception graph dataset descriptor for the JSON writer.
 */
export const misconceptionGraphDescriptor: JsonDatasetDescriptor = {
  directoryName: 'misconception-graph',
  typesModuleContent: [
    '/**',
    ' * Type definitions for the misconception graph.',
    ' *',
    ' * @remarks',
    ' * Generated by the misconception graph JSON writer.',
    ' * These interfaces describe the shape of `data.json`.',
    ' */',
    '',
    '/**',
    ' * A misconception node in the graph.',
    ' */',
    'export interface MisconceptionNode {',
    '  readonly misconception: string;',
    '  readonly response: string;',
    '  readonly subject: string;',
    '  readonly keyStage: string;',
    '  readonly lessonSlug: string;',
    '  readonly lessonTitle: string;',
    '}',
    '',
    '/**',
    ' * Statistics about the misconception graph.',
    ' */',
    'export interface MisconceptionGraphStats {',
    '  readonly totalMisconceptions: number;',
    '  readonly bySubject: Readonly<Record<string, number>>;',
    '  readonly byKeyStage: Readonly<Record<string, number>>;',
    '  readonly subjectsCovered: readonly string[];',
    '}',
    '',
    '/**',
    ' * The complete misconception graph structure.',
    ' */',
    'export interface MisconceptionGraph {',
    '  readonly version: string;',
    '  readonly generatedAt: string;',
    '  readonly sourceVersion: string;',
    '  readonly stats: MisconceptionGraphStats;',
    '  readonly nodes: readonly MisconceptionNode[];',
    '  readonly seeAlso: string;',
    '}',
    '',
  ].join('\n'),
  indexModuleContent: [
    '/**',
    ' * Misconception graph — typed loader for generated JSON data.',
    ' *',
    ' * @remarks',
    ' * Generated by the misconception graph JSON writer.',
    ' * Imports raw JSON data and re-exports it with TypeScript interfaces.',
    ' */',
    "import { createRequire } from 'node:module';",
    "import type { MisconceptionGraph } from './types.js';",
    '',
    'const require = createRequire(import.meta.url);',
    "const data: MisconceptionGraph = require('./data.json');",
    '',
    '/**',
    ' * Misconception graph with common mistakes and teacher responses.',
    ' *',
    ' * @remarks',
    ' * Contains misconceptions extracted from curriculum lessons.',
    ' * Use for identifying common mistakes and providing targeted support.',
    ' */',
    'export const misconceptionGraph: MisconceptionGraph = data;',
    '',
    "export type { MisconceptionGraph, MisconceptionGraphStats, MisconceptionNode } from './types.js';",
    '',
  ].join('\n'),
};

/**
 * Serializes a MisconceptionGraph to JSON.
 *
 * @param graph - The graph data to serialize
 * @returns Pretty-printed JSON string
 */
export function serializeMisconceptionGraph(graph: MisconceptionGraph): string {
  return serializeDatasetToJson(graph);
}

/**
 * Writes a misconception graph as JSON plus typed TypeScript modules.
 *
 * @param graph - The graph data to write
 * @param outputDir - Directory to write the file to
 * @returns Path to the created `misconception-graph` directory
 */
export async function writeMisconceptionGraphAsJson(
  graph: MisconceptionGraph,
  outputDir: string,
): Promise<string> {
  return writeJsonDataset(misconceptionGraphDescriptor, graph, outputDir);
}
