/**
 * NC coverage graph generator for the vocabulary mining pipeline.
 *
 * @remarks
 * Generates a graph of National Curriculum statement coverage from extracted data.
 * This graph helps curriculum planners ensure NC coverage and identify gaps.
 */
import type { Logger } from '@oaknational/logger';
import type { ExtractedNCStatement } from '../extractors/index.js';
import {
  serializeDatasetToJson,
  writeJsonDataset,
  type JsonDatasetDescriptor,
} from './write-json-dataset.js';

/**
 * An NC statement node in the graph.
 */
export interface NCStatementNode {
  /** The National Curriculum statement text */
  readonly statement: string;
  /** Unit that covers this statement */
  readonly unitSlug: string;
  /** Unit title for context */
  readonly unitTitle: string;
  /** Subject of the unit */
  readonly subject: string;
  /** Key stage of the unit */
  readonly keyStage: string;
}

/**
 * Statistics about the NC coverage graph.
 */
export interface NCCoverageGraphStats {
  /** Total number of NC statements */
  readonly totalStatements: number;
  /** Number of unique units covering statements */
  readonly uniqueUnits: number;
  /** Count of statements by subject */
  readonly bySubject: Readonly<Record<string, number>>;
  /** Count of statements by key stage */
  readonly byKeyStage: Readonly<Record<string, number>>;
  /** List of subjects covered */
  readonly subjectsCovered: readonly string[];
}

/**
 * The complete NC coverage graph structure.
 */
export interface NCCoverageGraph {
  /** Semantic version of this graph */
  readonly version: string;
  /** When this graph was generated */
  readonly generatedAt: string;
  /** Source data version */
  readonly sourceVersion: string;
  /** Statistics about the graph */
  readonly stats: NCCoverageGraphStats;
  /** All NC statement nodes */
  readonly nodes: readonly NCStatementNode[];
  /** Cross-reference to related resources */
  readonly seeAlso: string;
}

/**
 * Converts an extracted NC statement to a graph node.
 */
function toNode(statement: ExtractedNCStatement): NCStatementNode {
  return {
    statement: statement.statement,
    unitSlug: statement.unitSlug,
    unitTitle: statement.unitTitle,
    subject: statement.subject,
    keyStage: statement.keyStage,
  };
}

/**
 * Calculates statistics from NC statements.
 */
function calculateStats(statements: readonly ExtractedNCStatement[]): NCCoverageGraphStats {
  const bySubject: Record<string, number> = {};
  const byKeyStage: Record<string, number> = {};
  const subjects = new Set<string>();
  const units = new Set<string>();

  for (const s of statements) {
    bySubject[s.subject] = (bySubject[s.subject] ?? 0) + 1;
    byKeyStage[s.keyStage] = (byKeyStage[s.keyStage] ?? 0) + 1;
    subjects.add(s.subject);
    units.add(s.unitSlug);
  }

  return {
    totalStatements: statements.length,
    uniqueUnits: units.size,
    bySubject,
    byKeyStage,
    subjectsCovered: [...subjects].sort(),
  };
}

/**
 * Generates NC coverage graph data from extracted statements.
 *
 * @param statements - Array of extracted NC statements
 * @param sourceVersion - Version of the source bulk data
 * @returns NCCoverageGraph with all statements and statistics
 *
 * @example
 * ```ts
 * const graph = generateNCCoverageGraphData(extractedData.ncStatements, '2025-12-26');
 * console.log(`Found ${graph.stats.totalStatements} NC statements`);
 * ```
 */
export function generateNCCoverageGraphData(
  statements: readonly ExtractedNCStatement[],
  sourceVersion: string,
): NCCoverageGraph {
  return {
    version: '1.0.0',
    generatedAt: new Date().toISOString(),
    sourceVersion,
    stats: calculateStats(statements),
    nodes: statements.map(toNode),
    seeAlso: 'Use get-curriculum-model for complete orientation including curriculum structure',
  };
}

/**
 * NC coverage graph dataset descriptor for the JSON writer.
 */
export const ncCoverageGraphDescriptor: JsonDatasetDescriptor = {
  directoryName: 'nc-coverage-graph',
  typesModuleContent: [
    '/**',
    ' * Type definitions for the NC coverage graph.',
    ' *',
    ' * @remarks',
    ' * Generated by the NC coverage graph JSON writer.',
    ' * These interfaces describe the shape of `data.json`.',
    ' */',
    '',
    '/**',
    ' * An NC statement node in the graph.',
    ' */',
    'export interface NCStatementNode {',
    '  readonly statement: string;',
    '  readonly unitSlug: string;',
    '  readonly unitTitle: string;',
    '  readonly subject: string;',
    '  readonly keyStage: string;',
    '}',
    '',
    '/**',
    ' * Statistics about the NC coverage graph.',
    ' */',
    'export interface NCCoverageGraphStats {',
    '  readonly totalStatements: number;',
    '  readonly uniqueUnits: number;',
    '  readonly bySubject: Readonly<Record<string, number>>;',
    '  readonly byKeyStage: Readonly<Record<string, number>>;',
    '  readonly subjectsCovered: readonly string[];',
    '}',
    '',
    '/**',
    ' * The complete NC coverage graph structure.',
    ' */',
    'export interface NCCoverageGraph {',
    '  readonly version: string;',
    '  readonly generatedAt: string;',
    '  readonly sourceVersion: string;',
    '  readonly stats: NCCoverageGraphStats;',
    '  readonly nodes: readonly NCStatementNode[];',
    '  readonly seeAlso: string;',
    '}',
    '',
  ].join('\n'),
  indexModuleContent: [
    '/**',
    ' * NC coverage graph — typed loader for generated JSON data.',
    ' *',
    ' * @remarks',
    ' * Generated by the NC coverage graph JSON writer.',
    ' * Imports raw JSON data and re-exports it with TypeScript interfaces.',
    ' */',
    "import { createRequire } from 'node:module';",
    "import type { NCCoverageGraph } from './types.js';",
    '',
    'const require = createRequire(import.meta.url);',
    "const data: NCCoverageGraph = require('./data.json');",
    '',
    '/**',
    ' * NC coverage graph with National Curriculum statement mappings.',
    ' *',
    ' * @remarks',
    ' * Contains National Curriculum statement coverage across units.',
    ' * Use for curriculum planning and gap analysis.',
    ' */',
    'export const ncCoverageGraph: NCCoverageGraph = data;',
    '',
    "export type { NCCoverageGraph, NCCoverageGraphStats, NCStatementNode } from './types.js';",
    '',
  ].join('\n'),
};

/**
 * Serializes an NCCoverageGraph to JSON.
 *
 * @param graph - The graph data to serialize
 * @returns Pretty-printed JSON string
 */
export function serializeNCCoverageGraph(graph: NCCoverageGraph): string {
  return serializeDatasetToJson(graph);
}

/**
 * Writes an NC coverage graph as JSON plus typed TypeScript modules.
 *
 * @param graph - The graph data to write
 * @param outputDir - Directory to write the file to
 * @returns Path to the created `nc-coverage-graph` directory
 */
export async function writeNCCoverageGraphAsJson(
  graph: NCCoverageGraph,
  outputDir: string,
  logger?: Logger,
): Promise<string> {
  logger?.info('bulk.writer.write_nc_coverage_graph', {
    outputDir,
    sourceVersion: graph.sourceVersion,
  });
  return writeJsonDataset(ncCoverageGraphDescriptor, graph, outputDir, logger);
}
