/**
 * Vocabulary graph generator for the vocabulary mining pipeline.
 *
 * @remarks
 * Generates a graph of curriculum vocabulary from extracted keywords.
 * This graph provides a curated glossary for students and teachers,
 * with cross-subject term identification and first-year tracking.
 */
import type { ExtractedKeyword } from '../extractors/index.js';
import {
  serializeDatasetToJson,
  writeJsonDataset,
  type JsonDatasetDescriptor,
} from './write-json-dataset.js';

/**
 * A vocabulary node in the graph.
 */
export interface VocabularyNode {
  /** The vocabulary term */
  readonly term: string;
  /** Definition of the term */
  readonly definition: string;
  /** Number of lessons where this term appears */
  readonly frequency: number;
  /** Subjects where this term is used */
  readonly subjects: readonly string[];
  /** Earliest year this term is introduced */
  readonly firstYear: number;
  /** Whether this term appears in multiple subjects */
  readonly isCrossSubject: boolean;
}

/**
 * Statistics about the vocabulary graph.
 */
export interface VocabularyGraphStats {
  /** Total number of unique terms */
  readonly totalTerms: number;
  /** Count of terms by subject */
  readonly bySubject: Readonly<Record<string, number>>;
  /** Count of terms appearing in 2+ subjects */
  readonly crossSubjectTermCount: number;
  /** List of subjects covered */
  readonly subjectsCovered: readonly string[];
}

/**
 * The complete vocabulary graph structure.
 */
export interface VocabularyGraph {
  /** Semantic version of this graph */
  readonly version: string;
  /** When this graph was generated */
  readonly generatedAt: string;
  /** Source data version */
  readonly sourceVersion: string;
  /** Statistics about the graph */
  readonly stats: VocabularyGraphStats;
  /** All vocabulary nodes */
  readonly nodes: readonly VocabularyNode[];
  /** Cross-reference to related resources */
  readonly seeAlso: string;
}

/**
 * Converts an extracted keyword to a vocabulary node.
 */
function toNode(keyword: ExtractedKeyword): VocabularyNode {
  return {
    term: keyword.term,
    definition: keyword.definition,
    frequency: keyword.frequency,
    subjects: keyword.subjects,
    firstYear: keyword.firstYear,
    isCrossSubject: keyword.subjects.length >= 2,
  };
}

/**
 * Calculates statistics from keywords.
 */
function calculateStats(keywords: readonly ExtractedKeyword[]): VocabularyGraphStats {
  const bySubject: Record<string, number> = {};
  const allSubjects = new Set<string>();
  let crossSubjectCount = 0;

  for (const kw of keywords) {
    for (const subject of kw.subjects) {
      bySubject[subject] = (bySubject[subject] ?? 0) + 1;
      allSubjects.add(subject);
    }
    if (kw.subjects.length >= 2) {
      crossSubjectCount++;
    }
  }

  return {
    totalTerms: keywords.length,
    bySubject,
    crossSubjectTermCount: crossSubjectCount,
    subjectsCovered: [...allSubjects].sort(),
  };
}

/**
 * Generates vocabulary graph data from extracted keywords.
 *
 * @param keywords - Array of extracted keywords
 * @param sourceVersion - Version of the source bulk data
 * @returns VocabularyGraph with all vocabulary and statistics
 *
 * @example
 * ```ts
 * const graph = generateVocabularyGraphData(extractedData.keywords, '2025-12-26');
 * console.log(`Found ${graph.stats.totalTerms} vocabulary terms`);
 * ```
 */
export function generateVocabularyGraphData(
  keywords: readonly ExtractedKeyword[],
  sourceVersion: string,
): VocabularyGraph {
  return {
    version: '1.0.0',
    generatedAt: new Date().toISOString(),
    sourceVersion,
    stats: calculateStats(keywords),
    nodes: keywords.map(toNode),
    seeAlso: 'Use get-curriculum-model for complete orientation including curriculum structure',
  };
}

/**
 * Vocabulary graph dataset descriptor for the JSON writer.
 */
export const vocabularyGraphDescriptor: JsonDatasetDescriptor = {
  directoryName: 'vocabulary-graph',
  typesModuleContent: [
    '/**',
    ' * Type definitions for the vocabulary graph.',
    ' *',
    ' * @remarks',
    ' * Generated by the vocabulary graph JSON writer.',
    ' * These interfaces describe the shape of `data.json`.',
    ' */',
    '',
    '/**',
    ' * A vocabulary node in the graph.',
    ' */',
    'export interface VocabularyNode {',
    '  readonly term: string;',
    '  readonly definition: string;',
    '  readonly frequency: number;',
    '  readonly subjects: readonly string[];',
    '  readonly firstYear: number;',
    '  readonly isCrossSubject: boolean;',
    '}',
    '',
    '/**',
    ' * Statistics about the vocabulary graph.',
    ' */',
    'export interface VocabularyGraphStats {',
    '  readonly totalTerms: number;',
    '  readonly bySubject: Readonly<Record<string, number>>;',
    '  readonly crossSubjectTermCount: number;',
    '  readonly subjectsCovered: readonly string[];',
    '}',
    '',
    '/**',
    ' * The complete vocabulary graph structure.',
    ' */',
    'export interface VocabularyGraph {',
    '  readonly version: string;',
    '  readonly generatedAt: string;',
    '  readonly sourceVersion: string;',
    '  readonly stats: VocabularyGraphStats;',
    '  readonly nodes: readonly VocabularyNode[];',
    '  readonly seeAlso: string;',
    '}',
    '',
  ].join('\n'),
  indexModuleContent: [
    '/**',
    ' * Vocabulary graph — typed loader for generated JSON data.',
    ' *',
    ' * @remarks',
    ' * Generated by the vocabulary graph JSON writer.',
    ' * Imports raw JSON data and re-exports it with TypeScript interfaces.',
    ' */',
    "import { createRequire } from 'node:module';",
    "import type { VocabularyGraph } from './types.js';",
    '',
    'const require = createRequire(import.meta.url);',
    "const data: VocabularyGraph = require('./data.json');",
    '',
    '/**',
    ' * Vocabulary graph with curriculum terms and definitions.',
    ' *',
    ' * @remarks',
    ' * Contains curriculum vocabulary with definitions, frequency counts,',
    ' * and cross-subject identification.',
    ' * Use for glossary lookups and vocabulary progression queries.',
    ' */',
    'export const vocabularyGraph: VocabularyGraph = data;',
    '',
    "export type { VocabularyGraph, VocabularyGraphStats, VocabularyNode } from './types.js';",
    '',
  ].join('\n'),
};

/**
 * Serializes a VocabularyGraph to JSON.
 *
 * @param graph - The graph data to serialize
 * @returns Pretty-printed JSON string
 */
export function serializeVocabularyGraph(graph: VocabularyGraph): string {
  return serializeDatasetToJson(graph);
}

/**
 * Writes a vocabulary graph as JSON plus typed TypeScript modules.
 *
 * @param graph - The graph data to write
 * @param outputDir - Directory to write the file to
 * @returns Path to the created `vocabulary-graph` directory
 */
export async function writeVocabularyGraphAsJson(
  graph: VocabularyGraph,
  outputDir: string,
): Promise<string> {
  return writeJsonDataset(vocabularyGraphDescriptor, graph, outputDir);
}
