/* eslint max-lines:[error, 400] -- JC: static file generation */
/**
 * Utility for writing generated graph data to TypeScript files.
 *
 * @remarks
 * Handles serialization of graph data structures to TypeScript format
 * with proper `as const` annotations and TSDoc comments.

 */
import { writeFile } from 'fs/promises';
import { join } from 'path';

import type { Logger } from '@oaknational/logger';
import type { PriorKnowledgeGraph } from './prior-knowledge-graph-generator.js';
import type { ThreadProgressionGraph } from './thread-progression-generator.js';

/**
 * Escapes a string for use in TypeScript string literals.
 */
function escapeString(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

/**
 * Generates the file header with TSDoc.
 */
function generateHeader(graph: ThreadProgressionGraph): readonly string[] {
  return [
    '/**',
    ' * Thread Progression Graph — extracted from bulk download data.',
    ' *',
    ' * @remarks',
    ' * - Generated by `pnpm vocab-gen`',
    ` * - Source: ${graph.sourceVersion}`,
    ` * - Generated: ${graph.generatedAt}`,
    ' * - Contains ordered unit sequences within curriculum threads',
    ' * - Use for learning path recommendations and progression queries',
    ' *',
    ' * @see ADR-086 for extraction methodology',
    ' * @see property-graph-data.ts for the graph pattern',
    ' */',
    '',
  ];
}

/**
 * Generates the export TSDoc.
 */
function generateExportDoc(graph: ThreadProgressionGraph): readonly string[] {
  const { threadCount } = graph.stats;
  const subjectCount = graph.stats.subjectsCovered.length;

  return [
    '/**',
    ' * Thread progression graph with ordered unit sequences.',
    ' *',
    ' * @remarks',
    ` * Contains ${threadCount} threads across ${subjectCount} subjects.`,
    ' * Threads show conceptual progressions across years (e.g., "Number: Fractions" from Year 2-6).',
    ' *',
    ' * Use this to answer questions like:',
    ' * - "What\'s the learning path for fractions?"',
    ' * - "What comes after this unit in the thread?"',
    ' * - "Which threads cover algebra?"',
    ' */',
  ];
}

/**
 * Serializes a single thread node.
 */
function serializeThread(thread: ThreadProgressionGraph['threads'][number]): readonly string[] {
  const firstYearValue = thread.firstYear === undefined ? 'undefined' : thread.firstYear;
  const lastYearValue = thread.lastYear === undefined ? 'undefined' : thread.lastYear;

  return [
    '    {',
    `      slug: '${thread.slug}',`,
    `      title: '${escapeString(thread.title)}',`,
    `      subjects: ${JSON.stringify(thread.subjects)},`,
    `      firstYear: ${firstYearValue},`,
    `      lastYear: ${lastYearValue},`,
    `      unitCount: ${thread.unitCount},`,
    `      units: ${JSON.stringify(thread.units)},`,
    '    },',
  ];
}

/**
 * Generates the graph body with metadata and threads.
 */
function generateGraphBody(graph: ThreadProgressionGraph): readonly string[] {
  return [
    'export const threadProgressionGraph = {',
    `  version: '${graph.version}',`,
    `  generatedAt: '${graph.generatedAt}',`,
    `  sourceVersion: '${graph.sourceVersion}',`,
    '',
    '  stats: {',
    `    threadCount: ${graph.stats.threadCount},`,
    `    subjectsCovered: ${JSON.stringify(graph.stats.subjectsCovered)},`,
    '  },',
    '',
    '  threads: [',
    ...graph.threads.flatMap(serializeThread),
    '  ],',
    '',
    `  seeAlso: '${escapeString(graph.seeAlso)}',`,
    '} as const;',
    '',
  ];
}

/**
 * Generates the derived type exports.
 */
function generateTypeExports(): readonly string[] {
  return [
    '/**',
    ' * Type representing the complete thread progression graph.',
    ' */',
    'export type ThreadProgressionGraph = typeof threadProgressionGraph;',
    '',
    '/**',
    ' * Type representing a thread slug in the graph.',
    ' */',
    "export type ThreadSlug = ThreadProgressionGraph['threads'][number]['slug'];",
    '',
  ];
}

/**
 * Serializes a ThreadProgressionGraph to TypeScript source code.
 *
 * @param graph - The graph data to serialize
 * @returns TypeScript source code string
 */
export function serializeThreadProgressionGraph(graph: ThreadProgressionGraph): string {
  const lines: string[] = [
    ...generateHeader(graph),
    ...generateExportDoc(graph),
    ...generateGraphBody(graph),
    ...generateTypeExports(),
  ];

  return lines.join('\n');
}

/**
 * Writes a thread progression graph to a TypeScript file.
 *
 * @param graph - The graph data to write
 * @param outputDir - Directory to write the file to
 * @returns Path to the written file
 */
export async function writeThreadProgressionFile(
  graph: ThreadProgressionGraph,
  outputDir: string,
  logger?: Logger,
): Promise<string> {
  logger?.info('bulk.writer.write_thread_progression_graph', {
    outputDir,
    sourceVersion: graph.sourceVersion,
  });
  const fileName = 'thread-progression-data.ts';
  const filePath = join(outputDir, fileName);
  const content = serializeThreadProgressionGraph(graph);

  await writeFile(filePath, content, 'utf-8');

  return filePath;
}

// =============================================================================
// Prior Knowledge Graph Serialization
// =============================================================================

/**
 * Generates the file header for prior knowledge graph.
 */
function generatePriorKnowledgeHeader(graph: PriorKnowledgeGraph): readonly string[] {
  return [
    '/**',
    ' * Prior Knowledge Graph — extracted from bulk download data.',
    ' *',
    ' * @remarks',
    ' * - Generated by `pnpm vocab-gen`',
    ` * - Source: ${graph.sourceVersion}`,
    ` * - Generated: ${graph.generatedAt}`,
    ' * - Contains unit prerequisites and learning dependencies',
    ' * - Use for "what comes before" queries and learning path planning',
    ' *',
    ' * @see ADR-086 for extraction methodology',
    ' * @see property-graph-data.ts for the graph pattern',
    ' */',
    '',
  ];
}

/**
 * Generates the export TSDoc for prior knowledge graph.
 */
function generatePriorKnowledgeExportDoc(graph: PriorKnowledgeGraph): readonly string[] {
  const { unitsWithPrerequisites, totalEdges } = graph.stats;
  const subjectCount = graph.stats.subjectsCovered.length;

  return [
    '/**',
    ' * Prior knowledge graph with unit dependencies.',
    ' *',
    ' * @remarks',
    ` * Contains ${unitsWithPrerequisites} units with prerequisites and ${totalEdges} edges across ${subjectCount} subjects.`,
    ' * Edges represent prerequisiteFor relationships derived from thread ordering.',
    ' *',
    ' * Use this to answer questions like:',
    ' * - "What should students know before this unit?"',
    ' * - "What\'s the learning path to trigonometry?"',
    ' * - "Which units depend on this one?"',
    ' */',
  ];
}

/**
 * Serializes a single prior knowledge node.
 */
function serializePriorKnowledgeNode(
  node: PriorKnowledgeGraph['nodes'][number],
): readonly string[] {
  const yearValue = node.year === undefined ? 'undefined' : node.year;

  return [
    '    {',
    `      unitSlug: '${node.unitSlug}',`,
    `      unitTitle: '${escapeString(node.unitTitle)}',`,
    `      subject: '${node.subject}',`,
    `      keyStage: '${node.keyStage}',`,
    `      year: ${yearValue},`,
    `      priorKnowledge: ${JSON.stringify(node.priorKnowledge)},`,
    `      threadSlugs: ${JSON.stringify(node.threadSlugs)},`,
    '    },',
  ];
}

/**
 * Serializes a single prior knowledge edge.
 */
function serializePriorKnowledgeEdge(
  edge: PriorKnowledgeGraph['edges'][number],
): readonly string[] {
  return [
    `    { from: '${edge.from}', to: '${edge.to}', rel: '${edge.rel}', source: '${edge.source}' },`,
  ];
}

/**
 * Generates the prior knowledge graph body with metadata, nodes, and edges.
 *
 * @remarks
 * Uses explicit type annotation `: PriorKnowledgeGraph` instead of `as const`
 * because the graph is too large for TypeScript to serialize the literal type.
 */
function generatePriorKnowledgeGraphBody(graph: PriorKnowledgeGraph): readonly string[] {
  return [
    'export const priorKnowledgeGraph: PriorKnowledgeGraph = {',
    `  version: '${graph.version}',`,
    `  generatedAt: '${graph.generatedAt}',`,
    `  sourceVersion: '${graph.sourceVersion}',`,
    '',
    '  stats: {',
    `    unitsWithPrerequisites: ${graph.stats.unitsWithPrerequisites},`,
    `    totalEdges: ${graph.stats.totalEdges},`,
    `    subjectsCovered: ${JSON.stringify(graph.stats.subjectsCovered)},`,
    '  },',
    '',
    '  nodes: [',
    ...graph.nodes.flatMap(serializePriorKnowledgeNode),
    '  ],',
    '',
    '  edges: [',
    ...graph.edges.flatMap(serializePriorKnowledgeEdge),
    '  ],',
    '',
    `  seeAlso: '${escapeString(graph.seeAlso)}',`,
    '};',
    '',
  ];
}

/**
 * Generates the interface type definitions for prior knowledge graph.
 *
 * @remarks
 * We use explicit interface types rather than `typeof` because the graph
 * data is too large for TypeScript to serialize the literal type.
 */
function generatePriorKnowledgeTypeExports(): readonly string[] {
  return [
    '/**',
    ' * A prior knowledge edge in the graph.',
    ' */',
    'export interface PriorKnowledgeEdge {',
    '  readonly from: string;',
    '  readonly to: string;',
    "  readonly rel: 'prerequisiteFor';",
    "  readonly source: 'thread' | 'priorKnowledge';",
    '}',
    '',
    '/**',
    ' * A unit node in the prior knowledge graph.',
    ' */',
    'export interface PriorKnowledgeNode {',
    '  readonly unitSlug: string;',
    '  readonly unitTitle: string;',
    '  readonly subject: string;',
    '  readonly keyStage: string;',
    '  readonly year: number | undefined;',
    '  readonly priorKnowledge: readonly string[];',
    '  readonly threadSlugs: readonly string[];',
    '}',
    '',
    '/**',
    ' * Statistics about the prior knowledge graph.',
    ' */',
    'export interface PriorKnowledgeGraphStats {',
    '  readonly unitsWithPrerequisites: number;',
    '  readonly totalEdges: number;',
    '  readonly subjectsCovered: readonly string[];',
    '}',
    '',
    '/**',
    ' * The complete prior knowledge graph structure.',
    ' */',
    'export interface PriorKnowledgeGraph {',
    '  readonly version: string;',
    '  readonly generatedAt: string;',
    '  readonly sourceVersion: string;',
    '  readonly stats: PriorKnowledgeGraphStats;',
    '  readonly nodes: readonly PriorKnowledgeNode[];',
    '  readonly edges: readonly PriorKnowledgeEdge[];',
    '  readonly seeAlso: string;',
    '}',
    '',
  ];
}

/**
 * Serializes a PriorKnowledgeGraph to TypeScript source code.
 *
 * @param graph - The graph data to serialize
 * @returns TypeScript source code string
 *
 * @remarks
 * The order is: header → types → doc → data.
 * Types must come before the data export because the data uses the type annotation.
 */
export function serializePriorKnowledgeGraph(graph: PriorKnowledgeGraph): string {
  const lines: string[] = [
    ...generatePriorKnowledgeHeader(graph),
    ...generatePriorKnowledgeTypeExports(),
    ...generatePriorKnowledgeExportDoc(graph),
    ...generatePriorKnowledgeGraphBody(graph),
  ];

  return lines.join('\n');
}

/**
 * Writes a prior knowledge graph to a TypeScript file.
 *
 * @param graph - The graph data to write
 * @param outputDir - Directory to write the file to
 * @returns Path to the written file
 */
export async function writePriorKnowledgeGraphFile(
  graph: PriorKnowledgeGraph,
  outputDir: string,
  logger?: Logger,
): Promise<string> {
  logger?.info('bulk.writer.write_prior_knowledge_graph', {
    outputDir,
    sourceVersion: graph.sourceVersion,
  });
  const fileName = 'prior-knowledge-graph-data.ts';
  const filePath = join(outputDir, fileName);
  const content = serializePriorKnowledgeGraph(graph);

  await writeFile(filePath, content, 'utf-8');

  return filePath;
}
