/*
 * The shared static server over the canonical Claude Design export
 * (deduplicated from render-canonical-targets.ts and
 * drive-export-sections.ts): the .dc.html pages hydrate via _ds_bundle.js
 * and fetch data/quality-standards.json, so file:// is CORS-blocked — the
 * export must be served over local HTTP. Path resolution is a pure,
 * separately-testable decision (canonicalise, then prefix-check against the
 * served root) so the traversal guard has behaviour tests without IO.
 */
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { resolveWithinRoot } from '@oaknational/fidelity-review/static-path-guard';
import { err, ok, type Result } from '@oaknational/result';

const TOOLS_DIR = path.dirname(fileURLToPath(import.meta.url));

/** The untracked, byte-sacred canonical export directory. */
export const EXPORT_DIR = path.resolve(TOOLS_DIR, '..', 'claude-design-canonical-export');

const CONTENT_TYPES = new Map<string, string>([
  ['.html', 'text/html; charset=utf-8'],
  ['.js', 'text/javascript; charset=utf-8'],
  ['.css', 'text/css; charset=utf-8'],
  ['.json', 'application/json; charset=utf-8'],
  ['.ttf', 'font/ttf'],
  ['.woff2', 'font/woff2'],
  ['.svg', 'image/svg+xml'],
  ['.png', 'image/png'],
  ['.pdf', 'application/pdf'],
]);

/**
 * The traversal/decode guard is the shared static-path-guard (a malformed
 * percent-escape is a 404 decision there, never a URIError thrown inside
 * this module's http listener — the crash the local copy of this guard
 * used to carry).
 */
function handleStaticRequest(
  dir: string,
  req: http.IncomingMessage,
  res: http.ServerResponse,
): void {
  const resolved = resolveWithinRoot(dir, req.url ?? '/');
  const stat = resolved === undefined ? undefined : statServableFile(resolved);
  if (resolved === undefined || stat === undefined) {
    res.writeHead(404);
    res.end();
    return;
  }
  res.writeHead(200, {
    'content-type':
      CONTENT_TYPES.get(path.extname(resolved).toLowerCase()) ?? 'application/octet-stream',
  });
  const stream = fs.createReadStream(resolved);
  // An unreadable file (EACCES, vanished after the stat) emits 'error' on
  // the stream; without a listener that is an uncaught exception in the
  // listener. The headers are already written, so DESTROY the socket —
  // the browser then records a failed subresource request rather than a
  // clean 200 with a truncated body that could pass the capture
  // self-checks (e.g. an empty stylesheet under a styled-looking run).
  stream.on('error', (error: unknown) => {
    res.destroy(error instanceof Error ? error : new Error(String(error)));
  });
  stream.pipe(res);
}

/** Stat a candidate path, answering undefined for ANY lookup failure —
 *  ENOENT, but also e.g. ENOTDIR when a request uses an existing file as
 *  an intermediate segment ('/page.html/child'): every throw in the
 *  listener kills the run raw. isFile() also refuses FIFOs, whose open
 *  would block a libuv thread indefinitely. The single stat (no
 *  existsSync pre-probe) closes the vanish-between-probes window — the
 *  export tree is regenerated by the capture tooling. */
function statServableFile(candidate: string): fs.Stats | undefined {
  try {
    const stat = fs.statSync(candidate);
    return stat.isFile() ? stat : undefined;
  } catch {
    return undefined;
  }
}

/** Serve `dir` on an ephemeral localhost port. */
export function serveDir(dir: string): Promise<http.Server> {
  const server = http.createServer((req, res) => {
    handleStaticRequest(dir, req, res);
  });
  return new Promise((resolve) => {
    server.listen(0, '127.0.0.1', () => {
      resolve(server);
    });
  });
}

/** The bound TCP port of a listening server, narrowed from Node's address union. */
export function portOf(server: http.Server): Result<number, Error> {
  const address = server.address();
  if (address === null || typeof address === 'string') {
    return err(new Error('static server did not bind a TCP port'));
  }
  return ok(address.port);
}

/** Fail loud when the untracked export is absent (fresh clone, MCP re-pull owed). */
export function assertExportDir(): Result<void, string> {
  if (!fs.existsSync(EXPORT_DIR)) {
    return err(`export dir not found: ${EXPORT_DIR}`);
  }
  return ok(undefined);
}
