/**
 * MCP server OAuth 2.1 authentication policy.
 *
 * This file defines which tools require authentication and which are public.
 * Changes to this file trigger regeneration of all tool security metadata.
 *
 * @remarks
 * Tools NOT in PUBLIC_TOOLS require OAuth 2.1 authentication.
 * Tools in PUBLIC_TOOLS are publicly accessible without authentication.
 */

/**
 * List of tools that do not require OAuth authentication.
 *
 * These tools can be called without a Bearer token.
 * Typically used for discovery or public metadata endpoints.
 *
 * @example
 * ```typescript
 * // Make get-key-stages public
 * export const PUBLIC_TOOLS = ['get-key-stages'] as const;
 * ```
 */
export const PUBLIC_TOOLS: readonly string[] = [
  // Add tool names here to make them public
  // By default, all tools require authentication
  'get-changelog',
  'get-changelog-latest',
  'get-rate-limit',
] as const;

/**
 * Default OAuth 2.1 security scheme for protected tools.
 *
 * Applied to all tools NOT in PUBLIC_TOOLS list.
 *
 * @remarks
 * Protected MCP tools require only the minimum scope needed by the
 * server-side auth checks. Additional optional scopes are advertised via
 * {@link SUPPORTED_OAUTH_SCOPES} so dynamically registered clients can
 * request standard Clerk/OIDC scopes without making every tool require
 * them.
 */
export const DEFAULT_AUTH_SCHEME = {
  type: 'oauth2',
  scopes: ['email'],
} as const;

/**
 * OAuth scopes advertised in RFC 9728 protected resource metadata.
 *
 * These scopes are allowed for dynamically registered clients even when the
 * MCP tools themselves do not require them. Clerk-based clients commonly
 * request standard OIDC identity scopes plus refresh-token access.
 *
 * Keep `DEFAULT_AUTH_SCHEME.scopes` minimal for tool enforcement and expand
 * this list only when the authorisation server and client flows need broader
 * optional scope support.
 */
export const SUPPORTED_OAUTH_SCOPES = [
  'openid',
  'profile',
  'email',
  'offline_access',
  'public_metadata',
  'private_metadata',
] as const;

/**
 * Determines if a tool requires authentication based on policy.
 *
 * Pure function - always returns same result for same input.
 * Reads from PUBLIC_TOOLS configuration.
 *
 * @param toolName - MCP tool name
 * @returns true if tool requires auth, false if public
 */
export function toolRequiresAuth(toolName: string): boolean {
  return !PUBLIC_TOOLS.includes(toolName);
}

/**
 * Returns the OAuth scopes supported by this MCP server.
 *
 * All OAuth-protected tools in this server currently require the same scopes,
 * defined by DEFAULT_AUTH_SCHEME. This is a policy decision: we use a single
 * scope set for all protected operations.
 *
 * @returns Sorted array of supported OAuth scope strings
 *
 * @remarks
 * Used to generate RFC 9728 protected resource metadata at
 * `/.well-known/oauth-protected-resource`.
 *
 * **Current approach**: All protected tools share the same scopes.
 * If you need per-tool scope variation (e.g., different scopes for read vs write),
 * you'll need to:
 * 1. Update DEFAULT_AUTH_SCHEME to support per-tool configuration
 * 2. Update apply-security-policy.ts to use tool-specific scopes
 * 3. Replace this function with a generator that scans tool descriptors
 *
 * **Generated by**: code-generation/typegen/mcp-tools/parts/emit-index.ts
 * embeds these scopes into each tool descriptor's securitySchemes field.
 *
 * @see DEFAULT_AUTH_SCHEME for the OAuth scheme used by all protected tools
 */
export function getScopesSupported(): readonly string[] {
  // Sort for consistency in RFC 9728 metadata responses
  return [...SUPPORTED_OAUTH_SCOPES].sort();
}
