/**
 * MCP server OAuth 2.1 authentication policy.
 *
 * This file defines which tools require authentication and which are public.
 * Changes to this file trigger regeneration of all tool security metadata.
 *
 * @remarks
 * Tools NOT in PUBLIC_TOOLS require OAuth 2.1 authentication.
 * Tools in PUBLIC_TOOLS are publicly accessible without authentication.
 */

/**
 * List of tools that do not require OAuth authentication.
 *
 * These tools can be called without a Bearer token.
 * Typically used for discovery or public metadata endpoints.
 *
 * @example
 * ```typescript
 * // Make get-key-stages public
 * export const PUBLIC_TOOLS = ['get-key-stages'] as const;
 * ```
 */
export const PUBLIC_TOOLS: readonly string[] = [
  // Add tool names here to make them public
  // By default, all tools require authentication
  'get-changelog',
  'get-changelog-latest',
  'get-rate-limit',
] as const;

/**
 * Default OAuth 2.1 security scheme for protected tools.
 *
 * Applied to all tools NOT in PUBLIC_TOOLS list.
 *
 * @remarks
 * **Why `openid` is excluded**: Clerk rejects the `openid` (OIDC) scope for
 * dynamically registered clients (RFC 7591 DCR). Clerk accepts `openid` during
 * client registration but returns `error=invalid_scope` during authorisation.
 * This error is routed via redirect to the client's callback URL (per RFC 6749
 * Section 4.1.2.1), bypassing the server entirely and causing a silent failure
 * in clients like Cursor. MCP only needs an OAuth access token, not an OIDC ID
 * token, so `openid` is not required.
 *
 * Because `openid` is not in our PRM `scopes_supported`, compliant clients
 * (RFC 9728) will not request it. The proxy forwards all scopes transparently
 * without filtering.
 *
 * @see ADR-113 Troubleshooting section (docs/architecture/architectural-decisions/113-mcp-spec-compliant-auth-for-all-methods.md)
 */
export const DEFAULT_AUTH_SCHEME = {
  type: 'oauth2',
  scopes: ['email'],
} as const;

/**
 * Determines if a tool requires authentication based on policy.
 *
 * Pure function - always returns same result for same input.
 * Reads from PUBLIC_TOOLS configuration.
 *
 * @param toolName - MCP tool name
 * @returns true if tool requires auth, false if public
 */
export function toolRequiresAuth(toolName: string): boolean {
  return !PUBLIC_TOOLS.includes(toolName);
}

/**
 * Returns the OAuth scopes supported by this MCP server.
 *
 * All OAuth-protected tools in this server currently require the same scopes,
 * defined by DEFAULT_AUTH_SCHEME. This is a policy decision: we use a single
 * scope set for all protected operations.
 *
 * @returns Sorted array of supported OAuth scope strings
 *
 * @remarks
 * Used to generate RFC 9728 protected resource metadata at
 * `/.well-known/oauth-protected-resource`.
 *
 * **Current approach**: All protected tools share the same scopes.
 * If you need per-tool scope variation (e.g., different scopes for read vs write),
 * you'll need to:
 * 1. Update DEFAULT_AUTH_SCHEME to support per-tool configuration
 * 2. Update apply-security-policy.ts to use tool-specific scopes
 * 3. Replace this function with a generator that scans tool descriptors
 *
 * **Generated by**: code-generation/typegen/mcp-tools/parts/emit-index.ts
 * embeds these scopes into each tool descriptor's securitySchemes field.
 *
 * @see DEFAULT_AUTH_SCHEME for the OAuth scheme used by all protected tools
 */
export function getScopesSupported(): readonly string[] {
  // Sort for consistency in RFC 9728 metadata responses
  return [...DEFAULT_AUTH_SCHEME.scopes].sort();
}
