/**
 * MCP server OAuth 2.1 authentication policy.
 *
 * This file defines which tools require authentication and which are public.
 * Changes to this file trigger regeneration of all tool security metadata.
 *
 * @remarks
 * Tools NOT in PUBLIC_TOOLS require OAuth 2.1 authentication with the
 * DEFAULT_AUTH_SCHEME scopes. Tools in PUBLIC_TOOLS skip only the per-tool
 * OAuth scope check: the HTTP transport still requires a bearer token for
 * every tool call, and an unauthenticated call receives 401.
 */

/**
 * List of tools that skip the per-tool OAuth scope check.
 *
 * `noauth` means no scope requirement, not anonymous access — the HTTP
 * transport still demands a bearer token for every tool call and returns
 * 401 without one. Typically used for discovery or metadata tools whose
 * responses carry no scope-gated content.
 *
 * @example
 * ```typescript
 * // Exempt get-key-stages from the scope check
 * export const PUBLIC_TOOLS = ['get-key-stages'] as const;
 * ```
 */
export const PUBLIC_TOOLS: readonly string[] = [
  // Add tool names here to skip the per-tool scope check
  // By default, all tools carry the DEFAULT_AUTH_SCHEME scopes
  'get-rate-limit',
] as const;

/**
 * Default OAuth 2.1 security scheme for protected tools.
 *
 * Applied to all tools NOT in PUBLIC_TOOLS list.
 *
 * @remarks
 * **Why `openid` is excluded**: Oak's policy choice, not a Clerk ceiling. This
 * is an OAuth 2.1 resource server: it authorises from an access token and reads
 * no OIDC identity claims, so an ID token buys it nothing. Clerk grants a
 * dynamically registered client (RFC 7591 DCR) the scopes named in its
 * registration plus `offline_access`, or the instance default grant when it
 * names none; a registration that omits `openid` is not granted it (measured
 * 2026-08-19: `openid email` registered, `email offline_access openid`
 * granted; ADR-113, Evidence: the DCR grant probe). Oak's default grant
 * carries no `openid`; a client that requests it outside its grant receives
 * `error=invalid_scope`, routed via redirect to the client's callback URL (RFC
 * 6749 Section 4.1.2.1), bypassing the server and failing silently in clients
 * like Cursor. (Mechanism corrected 2026-09-08, MCP-345; the earlier wording
 * called it a platform rule.)
 *
 * Because `openid` is not in our PRM `scopes_supported`, clients that choose
 * their scopes from the PRM (RFC 9728) will not request it; a client may still
 * ask for scopes of its own. Since MCP-345 the served authorization-server
 * metadata advertises this same set, so clients that choose scopes from that
 * document (ChatGPT's plugin portal, measured 2026-09-08) do not request it
 * either. The proxy still forwards the `scope` a client sends unchanged.
 *
 * @see ADR-113 Troubleshooting section (docs/architecture/architectural-decisions/113-mcp-spec-compliant-auth-for-all-methods.md)
 */
export const DEFAULT_AUTH_SCHEME = {
  type: 'oauth2',
  scopes: ['email'],
} as const;

/**
 * Determines if a tool requires authentication based on policy.
 *
 * Pure function - always returns same result for same input.
 * Reads from PUBLIC_TOOLS configuration.
 *
 * @param toolName - MCP tool name
 * @returns true if tool requires auth, false if public
 */
export function toolRequiresAuth(toolName: string): boolean {
  return !PUBLIC_TOOLS.includes(toolName);
}

/**
 * Returns the OAuth scopes supported by this MCP server.
 *
 * All OAuth-protected tools in this server currently require the same scopes,
 * defined by DEFAULT_AUTH_SCHEME. This is a policy decision: we use a single
 * scope set for all protected operations.
 *
 * @returns Sorted array of supported OAuth scope strings
 *
 * @remarks
 * Used to generate RFC 9728 protected resource metadata at
 * `/.well-known/oauth-protected-resource`, and served as the `scopes_supported`
 * of the RFC 8414 authorization-server metadata at
 * `/.well-known/oauth-authorization-server` (MCP-345).
 *
 * **Current approach**: All protected tools share the same scopes.
 * If you need per-tool scope variation (e.g., different scopes for read vs write),
 * you'll need to:
 * 1. Update DEFAULT_AUTH_SCHEME to support per-tool configuration
 * 2. Update apply-security-policy.ts to use tool-specific scopes
 * 3. Replace this function with a generator that scans tool descriptors
 *
 * **Generated by**: code-generation/typegen/mcp-tools/parts/emit-index.ts
 * embeds these scopes into each tool descriptor's securitySchemes field.
 *
 * @see DEFAULT_AUTH_SCHEME for the OAuth scheme used by all protected tools
 */
export function getScopesSupported(): readonly string[] {
  // Sort for consistency in RFC 9728 metadata responses
  return [...DEFAULT_AUTH_SCHEME.scopes].sort((a, b) => a.localeCompare(b));
}
