/**
 * Unit tests for schema separation functionality
 * Following TDD approach - tests written before implementation
 */

import { describe, it, expect } from 'vitest';
import type { OpenAPIObject, SchemaObject } from 'openapi3-ts/oas31';

import { createOpenCurriculumSchema } from './schema-separation-core.js';
import { schemaWithNestedResponses } from './test-fixtures.js';

function buildTranscriptSchema(): OpenAPIObject {
  return {
    openapi: '3.0.3',
    info: { title: 'Oak OpenAPI', version: '1.0.0' },
    paths: {
      '/lessons/{lesson}/transcript': {
        get: {
          operationId: 'getLessonTranscript',
          responses: {
            '200': {
              description: 'Successful response',
            },
          },
        },
      },
    },
    components: {
      schemas: {
        TranscriptResponseSchema: {
          type: 'object',
          properties: {
            transcript: { type: 'string' },
          },
        },
      },
    },
  };
}

function isSchemaObject(value: unknown): value is SchemaObject {
  if (typeof value !== 'object' || value === null) {
    return false;
  }
  return !('$ref' in value);
}

describe('schema separation', () => {
  describe('createOpenCurriculumSchema', () => {
    it('returns original clone and decorated SDK schema without mutating the input', () => {
      const validatedSchema = buildTranscriptSchema();
      validatedSchema.components = {
        ...validatedSchema.components,
        schemas: {
          ...(validatedSchema.components?.schemas ?? {}),
          LessonResponse: {
            type: 'object',
            properties: {
              title: { type: 'string' },
            },
          },
        },
      };

      const { original, sdk } = createOpenCurriculumSchema(validatedSchema);

      expect(original).toEqual(validatedSchema);
      expect(original).not.toBe(validatedSchema);

      const lessonResponse = sdk.components?.schemas?.LessonResponse;
      if (!lessonResponse || !isSchemaObject(lessonResponse) || !lessonResponse.properties) {
        throw new Error('LessonResponse schema or properties missing');
      }
      expect(lessonResponse.properties).toHaveProperty('canonicalUrl');
      expect(lessonResponse.properties.canonicalUrl).toHaveProperty('type', 'string');

      const originalLesson = original.components?.schemas?.LessonResponse;
      if (!originalLesson || !isSchemaObject(originalLesson) || !originalLesson.properties) {
        throw new Error('Original LessonResponse schema or properties missing');
      }
      expect(originalLesson.properties).not.toHaveProperty('canonicalUrl');
    });

    it('preserves all original schema fields while adding canonicalUrl', () => {
      const validatedSchema = buildTranscriptSchema();
      validatedSchema.components = {
        ...validatedSchema.components,
        schemas: {
          ...(validatedSchema.components?.schemas ?? {}),
          LessonResponse: {
            type: 'object',
            properties: {
              title: { type: 'string' },
              description: { type: 'string' },
            },
          },
        },
      };

      const { original, sdk } = createOpenCurriculumSchema(validatedSchema);

      const lessonResponse = sdk.components?.schemas?.LessonResponse;
      if (!lessonResponse || !isSchemaObject(lessonResponse) || !lessonResponse.properties) {
        throw new Error('LessonResponse schema or properties missing');
      }
      expect(lessonResponse.properties.title).toEqual({ type: 'string' });
      expect(lessonResponse.properties.description).toEqual({ type: 'string' });
      expect(lessonResponse.properties.canonicalUrl).toEqual({
        type: 'string',
        description: 'The canonical URL for this resource, generated by the SDK',
        example: 'https://www.thenational.academy/teachers/lessons/example-lesson',
      });

      const originalLesson = original.components?.schemas?.LessonResponse;
      if (!originalLesson || !isSchemaObject(originalLesson) || !originalLesson.properties) {
        throw new Error('Original LessonResponse schema or properties missing');
      }
      expect(originalLesson.properties).not.toHaveProperty('canonicalUrl');
    });

    it('should add canonicalUrl to nested response schemas without mutating input', () => {
      const { original, sdk } = createOpenCurriculumSchema(schemaWithNestedResponses);

      const originalLesson = original.components?.schemas?.LessonResponse;
      const sdkLesson = sdk.components?.schemas?.LessonResponse;

      if (!originalLesson || !sdkLesson || !('properties' in sdkLesson)) {
        throw new Error('LessonResponse schema not present');
      }

      if (!isSchemaObject(originalLesson) || !isSchemaObject(sdkLesson)) {
        throw new Error('Expected SchemaObject for LessonResponse');
      }
      expect(originalLesson.properties?.canonicalUrl).toBeUndefined();
      expect(sdkLesson.properties?.canonicalUrl).toEqual({
        type: 'string',
        description: 'The canonical URL for this resource, generated by the SDK',
        example: 'https://www.thenational.academy/teachers/lessons/example-lesson',
      });

      const searchResponse = sdk.components?.schemas?.SearchResponse;
      if (!searchResponse || !isSchemaObject(searchResponse) || !searchResponse.properties) {
        throw new Error('SearchResponse schema or properties missing');
      }
      const summarySchema = searchResponse.properties.summary;
      if (!summarySchema || !isSchemaObject(summarySchema) || !Array.isArray(summarySchema.anyOf)) {
        throw new Error('SearchResponse.summary.anyOf missing');
      }
      expect(summarySchema.anyOf).toHaveLength(2);
    });
  });
});
