/**
 * Core document builder for the oak_lessons Elasticsearch index.
 *
 * This module is the **single source of truth** for lesson document creation,
 * used by both API and bulk ingestion paths (DRY compliance).
 *
 * The input-agnostic `CreateLessonDocParams` interface allows both paths to
 * provide extracted values without coupling to specific input types.
 *
 * @see SearchLessonsIndexDoc - The Zod-validated type this produces
 * @see transformBulkLessonToESDoc - Bulk path adapter that delegates here
 * @see createLessonDocument - API path function in document-transforms.ts

 */

import type {
  KeyStage,
  SearchLessonsIndexDoc,
  AllSubjectSlug,
  ParentSubjectSlug,
} from '../../types/oak';
import type { Ks4DocumentFields } from './document-transform-helpers';
import {
  copyArrayOrUndefined,
  derivePhaseFromKeyStage,
  extractUnitArrays,
} from './lesson-document-core.helpers';

/**
 * Unit information for lesson documents.
 * Lessons may belong to multiple units.
 */
export interface LessonUnitInfo {
  /** Unit slug identifier */
  readonly unitSlug: string;
  /** Unit display title */
  readonly unitTitle: string;
  /** Unit canonical URL */
  readonly canonicalUrl: string;
}

/**
 * Input-agnostic parameters for creating a lesson document.
 *
 * This interface contains **extracted values** rather than raw input types,
 * allowing both API and bulk paths to provide data without coupling.
 *
 * @example API path extraction:
 * ```typescript
 * const params: CreateLessonDocParams = {
 *   lessonSlug: summary.lessonSlug,
 *   lessonTitle: summary.lessonTitle,
 *   subjectSlug: subject,
 *   subjectTitle: summary.subjectTitle,
 *   // ... extract other fields from SearchLessonSummary
 * };
 * ```
 *
 * @example Bulk path extraction:
 * ```typescript
 * const params: CreateLessonDocParams = {
 *   lessonSlug: lesson.lessonSlug,
 *   lessonTitle: lesson.lessonTitle,
 *   subjectSlug: normalisedSubject,
 *   subjectTitle: lesson.subjectTitle,
 *   // ... extract other fields from Lesson
 * };
 * ```
 */
export interface CreateLessonDocParams {
  // === Identity ===
  /** Lesson slug identifier */
  readonly lessonSlug: string;
  /** Lesson display title */
  readonly lessonTitle: string;

  // === Subject/KeyStage ===
  /**
   * Subject slug - the actual subject from bulk data.
   * For KS4 science, this may be 'physics', 'chemistry', 'biology', or 'combined-science'.
   * @see AllSubjectSlug - Includes all 21 valid subjects
   */
  readonly subjectSlug: AllSubjectSlug;
  /**
   * Subject parent - the parent subject for hierarchical filtering.
   * For KS4 science variants, this is 'science'.
   * For other subjects, this equals subjectSlug.
   * @see ParentSubjectSlug - The 17 canonical subjects
   * @see ADR-101 for subject hierarchy design
   */
  readonly subjectParent: ParentSubjectSlug;
  /** Subject display title */
  readonly subjectTitle: string;
  /** Key stage slug (validated KeyStage) */
  readonly keyStage: KeyStage;
  /** Key stage display title */
  readonly keyStageTitle: string;

  // === Years ===
  /** Year groups this lesson covers */
  readonly years: readonly string[] | undefined;

  // === Unit relationships ===
  /** Units this lesson belongs to (at least one required) */
  readonly units: readonly LessonUnitInfo[];
  /** Total unit count for display */
  readonly unitCount: number;

  // === Thread relationships ===
  /** Curriculum thread slugs associated with the lesson. */
  readonly threadSlugs?: readonly string[];
  /** Curriculum thread titles associated with the lesson. */
  readonly threadTitles?: readonly string[];

  // === Pedagogical fields ===
  /** Extracted keyword strings */
  readonly lessonKeywords: readonly string[] | undefined;
  /** Extracted key learning point strings */
  readonly keyLearningPoints: readonly string[] | undefined;
  /** Extracted misconception strings (formatted as "misconception → response") */
  readonly misconceptions: readonly string[] | undefined;
  /** Extracted teacher tip strings */
  readonly teacherTips: readonly string[] | undefined;
  /** Extracted content guidance labels */
  readonly contentGuidance: readonly string[] | undefined;

  // === Content ===
  /**
   * Lesson transcript text.
   * When undefined, null, or empty, content fields are omitted to avoid
   * polluting BM25/ELSER indexes.
   * @see ADR-095 for rationale
   */
  readonly transcript: string | undefined | null;
  /**
   * Pre-generated semantic summary for ELSER embeddings.
   * This is generated by the caller (API or bulk path) to allow
   * path-specific optimisations.
   */
  readonly lessonStructure: string;

  // === Metadata ===
  /** Lesson canonical URL */
  readonly lessonUrl: string;
  /** Pupil lesson outcome text */
  readonly pupilLessonOutcome: string | undefined;
  /** Supervision level (normalised) */
  readonly supervisionLevel: string | undefined;
  /** Whether downloads are available */
  readonly downloadsAvailable: boolean | undefined;

  // === KS4 (optional) ===
  /**
   * KS4 metadata fields.
   * For bulk path: typically undefined (added in post-processing via enrichment)
   * For API path: typically provided from unitContextMap
   */
  readonly ks4?: Ks4DocumentFields;
}

/**
 * Creates an Elasticsearch document for the oak_lessons index.
 *
 * This is the **shared builder** for lesson documents, providing a single source
 * of truth for document creation logic. Both API and bulk ingestion paths
 * delegate to this function.
 *
 * Content fields (`lesson_content`, `lesson_content_semantic`) are conditionally
 * included based on transcript availability. Structure fields are always populated.
 *
 * @param params - Lesson data extracted from any source (API or bulk)
 * @returns A valid SearchLessonsIndexDoc ready for Elasticsearch indexing
 *
 * @see ADR-094 for `has_transcript` field rationale
 * @see ADR-095 for conditional field inclusion rationale
 */
export function buildLessonDocument(params: CreateLessonDocParams): SearchLessonsIndexDoc {
  const { lessonSlug, lessonTitle, subjectSlug, subjectParent, keyStage, units } = params;

  if (units.length === 0) {
    throw new Error(`Lesson ${lessonSlug} has no unit relationships`);
  }

  const hasTranscript = typeof params.transcript === 'string' && params.transcript.length > 0;
  const { unitIds, unitTitles, unitUrls } = extractUnitArrays(units);

  return {
    lesson_id: lessonSlug,
    lesson_slug: lessonSlug,
    lesson_title: lessonTitle,
    subject_slug: subjectSlug,
    subject_parent: subjectParent,
    subject_title: params.subjectTitle,
    key_stage: keyStage,
    key_stage_title: params.keyStageTitle,
    phase_slug: derivePhaseFromKeyStage(keyStage),
    years: copyArrayOrUndefined(params.years),
    unit_ids: unitIds,
    unit_titles: unitTitles,
    unit_count: params.unitCount,
    unit_urls: unitUrls,
    thread_slugs: copyArrayOrUndefined(params.threadSlugs),
    thread_titles: copyArrayOrUndefined(params.threadTitles),
    lesson_keywords: copyArrayOrUndefined(params.lessonKeywords),
    key_learning_points: copyArrayOrUndefined(params.keyLearningPoints),
    misconceptions_and_common_mistakes: copyArrayOrUndefined(params.misconceptions),
    teacher_tips: copyArrayOrUndefined(params.teacherTips),
    content_guidance: copyArrayOrUndefined(params.contentGuidance),
    has_transcript: hasTranscript,
    lesson_content: hasTranscript ? params.transcript : undefined,
    lesson_content_semantic: hasTranscript ? params.transcript : undefined,
    lesson_structure: params.lessonStructure,
    lesson_structure_semantic: params.lessonStructure,
    lesson_url: params.lessonUrl,
    pupil_lesson_outcome: params.pupilLessonOutcome,
    supervision_level: params.supervisionLevel,
    downloads_available: params.downloadsAvailable,
    ...params.ks4,
    title_suggest: {
      input: [lessonTitle],
      contexts: { subject: [subjectSlug], key_stage: [keyStage] },
    },
    doc_type: 'lesson',
  };
}
