/**
 * Embeds the built widget HTML into a committed TypeScript constant.
 *
 * Reads the Vite-built single-file HTML from `.widget-build/oak-banner.html`
 * and writes `src/generated/widget-html-content.ts` — a regular TypeScript
 * module that exports the HTML as a string constant.
 *
 * This follows the same codegen pattern as `widget-constants.ts` and other
 * generated SDK metadata: produce a committed `.ts` file at codegen time,
 * import it normally at runtime.
 *
 * @see widget/vite.config.ts — Widget build configuration
 * @see widget/oak-banner.html — Widget entry point
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const appRoot = resolve(scriptDir, '..');
const inputPath = resolve(appRoot, '.widget-build/oak-banner.html');
const outputPath = resolve(appRoot, 'src/generated/widget-html-content.ts');

function isErrnoException(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && 'code' in error;
}

let html: string;
try {
  html = readFileSync(inputPath, 'utf-8');
} catch (error) {
  if (isErrnoException(error) && error.code === 'ENOENT') {
    process.stderr.write(
      `Widget HTML not found at ${inputPath}.\n` +
        'Vite must build the widget before the embed script runs.\n' +
        'Run: pnpm build:widget (which chains Vite → embed automatically)\n',
    );
    process.exit(1);
  }
  throw error;
}
const escaped = html.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

mkdirSync(dirname(outputPath), { recursive: true });

const output = `/**
 * GENERATED FILE — DO NOT EDIT
 *
 * Built widget HTML content generated by the widget build step.
 * Re-generate by running: pnpm build:widget
 *
 * @see widget/vite.config.ts - Widget build configuration
 * @see widget/oak-banner.html - Widget entry point
 */
export const WIDGET_HTML_CONTENT = \`${escaped}\` as const;
`;

writeFileSync(outputPath, output, 'utf-8');

const sizeKb = (Buffer.byteLength(html, 'utf-8') / 1024).toFixed(1);
process.stdout.write(
  `Embedded widget HTML (${sizeKb} KB) → src/generated/widget-html-content.ts\n`,
);
