/* eslint-disable max-lines -- generator with serialisation requires length */

/**
 * NC coverage graph generator for the vocabulary mining pipeline.
 *
 * @remarks
 * Generates a graph of National Curriculum statement coverage from extracted data.
 * This graph helps curriculum planners ensure NC coverage and identify gaps.

 */
import { writeFile } from 'fs/promises';
import { join } from 'path';

import type { ExtractedNCStatement } from '../extractors/index.js';

/**
 * An NC statement node in the graph.
 */
export interface NCStatementNode {
  /** The National Curriculum statement text */
  readonly statement: string;
  /** Unit that covers this statement */
  readonly unitSlug: string;
  /** Unit title for context */
  readonly unitTitle: string;
  /** Subject of the unit */
  readonly subject: string;
  /** Key stage of the unit */
  readonly keyStage: string;
}

/**
 * Statistics about the NC coverage graph.
 */
export interface NCCoverageGraphStats {
  /** Total number of NC statements */
  readonly totalStatements: number;
  /** Number of unique units covering statements */
  readonly uniqueUnits: number;
  /** Count of statements by subject */
  /** Keys are curriculum subject slugs (runtime-defined). */
  readonly bySubject: Readonly<Record<string, number>>;
  /** Count of statements by key stage. Keys are key stage slugs (runtime-defined). */
  readonly byKeyStage: Readonly<Record<string, number>>;
  /** List of subjects covered */
  readonly subjectsCovered: readonly string[];
}

/**
 * The complete NC coverage graph structure.
 */
export interface NCCoverageGraph {
  /** Semantic version of this graph */
  readonly version: string;
  /** When this graph was generated */
  readonly generatedAt: string;
  /** Source data version */
  readonly sourceVersion: string;
  /** Statistics about the graph */
  readonly stats: NCCoverageGraphStats;
  /** All NC statement nodes */
  readonly nodes: readonly NCStatementNode[];
  /** Cross-reference to related resources */
  readonly seeAlso: string;
}

/**
 * Converts an extracted NC statement to a graph node.
 */
function toNode(statement: ExtractedNCStatement): NCStatementNode {
  return {
    statement: statement.statement,
    unitSlug: statement.unitSlug,
    unitTitle: statement.unitTitle,
    subject: statement.subject,
    keyStage: statement.keyStage,
  };
}

/**
 * Calculates statistics from NC statements.
 */
function calculateStats(statements: readonly ExtractedNCStatement[]): NCCoverageGraphStats {
  const bySubject: Record<string, number> = {};
  const byKeyStage: Record<string, number> = {};
  const subjects = new Set<string>();
  const units = new Set<string>();

  for (const s of statements) {
    bySubject[s.subject] = (bySubject[s.subject] ?? 0) + 1;
    byKeyStage[s.keyStage] = (byKeyStage[s.keyStage] ?? 0) + 1;
    subjects.add(s.subject);
    units.add(s.unitSlug);
  }

  return {
    totalStatements: statements.length,
    uniqueUnits: units.size,
    bySubject,
    byKeyStage,
    subjectsCovered: [...subjects].sort(),
  };
}

/**
 * Generates NC coverage graph data from extracted statements.
 *
 * @param statements - Array of extracted NC statements
 * @param sourceVersion - Version of the source bulk data
 * @returns NCCoverageGraph with all statements and statistics
 *
 * @example
 * ```ts
 * const graph = generateNCCoverageGraphData(extractedData.ncStatements, '2025-12-26');
 * console.log(`Found ${graph.stats.totalStatements} NC statements`);
 * ```
 */
export function generateNCCoverageGraphData(
  statements: readonly ExtractedNCStatement[],
  sourceVersion: string,
): NCCoverageGraph {
  return {
    version: '1.0.0',
    generatedAt: new Date().toISOString(),
    sourceVersion,
    stats: calculateStats(statements),
    nodes: statements.map(toNode),
    seeAlso: 'Use get-ontology for curriculum structure context',
  };
}

/**
 * Escapes a string for use in TypeScript string literals.
 */
function escapeString(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r');
}

/**
 * Serializes an NCCoverageGraph to TypeScript source code.
 *
 * @param graph - The graph data to serialize
 * @returns TypeScript source code string
 */
export function serializeNCCoverageGraph(graph: NCCoverageGraph): string {
  const lines: string[] = [
    '/* eslint-disable max-lines -- generated static data file */',
    '/**',
    ' * NC Coverage Graph — extracted from bulk download data.',
    ' *',
    ' * @remarks',
    ' * - Generated by `pnpm vocab-gen`',
    ` * - Source: ${graph.sourceVersion}`,
    ` * - Generated: ${graph.generatedAt}`,
    ' * - Contains National Curriculum statement coverage mapping',
    ' * - Use for curriculum planning and NC coverage analysis',
    ' *',
    ' * @see ADR-086 for extraction methodology',
    ' */',
    '',
    '/**',
    ' * An NC statement node in the graph.',
    ' */',
    'export interface NCStatementNode {',
    '  readonly statement: string;',
    '  readonly unitSlug: string;',
    '  readonly unitTitle: string;',
    '  readonly subject: string;',
    '  readonly keyStage: string;',
    '}',
    '',
    '/**',
    ' * Statistics about the NC coverage graph.',
    ' */',
    'export interface NCCoverageGraphStats {',
    '  readonly totalStatements: number;',
    '  readonly uniqueUnits: number;',
    '  readonly bySubject: Readonly<Record<string, number>>;',
    '  readonly byKeyStage: Readonly<Record<string, number>>;',
    '  readonly subjectsCovered: readonly string[];',
    '}',
    '',
    '/**',
    ' * The complete NC coverage graph structure.',
    ' */',
    'export interface NCCoverageGraph {',
    '  readonly version: string;',
    '  readonly generatedAt: string;',
    '  readonly sourceVersion: string;',
    '  readonly stats: NCCoverageGraphStats;',
    '  readonly nodes: readonly NCStatementNode[];',
    '  readonly seeAlso: string;',
    '}',
    '',
    '/**',
    ' * NC coverage graph with curriculum statement mappings.',
    ' *',
    ' * @remarks',
    ` * Contains ${graph.stats.totalStatements} statements across ${graph.stats.subjectsCovered.length} subjects.`,
    ` * Coverage spans ${graph.stats.uniqueUnits} unique units.`,
    ' *',
    ' * Use this to answer questions like:',
    ' * - "Which units cover this NC statement?"',
    ' * - "What is the NC coverage for this subject?"',
    ' * - "Which NC statements are covered in this key stage?"',
    ' */',
    'export const ncCoverageGraph: NCCoverageGraph = {',
    `  version: '${graph.version}',`,
    `  generatedAt: '${graph.generatedAt}',`,
    `  sourceVersion: '${graph.sourceVersion}',`,
    '',
    '  stats: {',
    `    totalStatements: ${graph.stats.totalStatements},`,
    `    uniqueUnits: ${graph.stats.uniqueUnits},`,
    `    bySubject: ${JSON.stringify(graph.stats.bySubject)},`,
    `    byKeyStage: ${JSON.stringify(graph.stats.byKeyStage)},`,
    `    subjectsCovered: ${JSON.stringify(graph.stats.subjectsCovered)},`,
    '  },',
    '',
    '  nodes: [',
  ];

  // Add nodes
  for (const node of graph.nodes) {
    lines.push('    {');
    lines.push(`      statement: '${escapeString(node.statement)}',`);
    lines.push(`      unitSlug: '${node.unitSlug}',`);
    lines.push(`      unitTitle: '${escapeString(node.unitTitle)}',`);
    lines.push(`      subject: '${node.subject}',`);
    lines.push(`      keyStage: '${node.keyStage}',`);
    lines.push('    },');
  }

  lines.push('  ],');
  lines.push('');
  lines.push(`  seeAlso: '${escapeString(graph.seeAlso)}',`);
  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

/**
 * Writes an NC coverage graph to a TypeScript file.
 *
 * @param graph - The graph data to write
 * @param outputDir - Directory to write the file to
 * @returns Path to the written file
 */
export async function writeNCCoverageGraphFile(
  graph: NCCoverageGraph,
  outputDir: string,
): Promise<string> {
  const fileName = 'nc-coverage-graph-data.ts';
  const filePath = join(outputDir, fileName);
  const content = serializeNCCoverageGraph(graph);

  await writeFile(filePath, content, 'utf-8');

  return filePath;
}
