/**
 * Unit tests for schema separation functionality
 * Following TDD approach - tests written before implementation
 */

/* eslint-disable @typescript-eslint/no-unsafe-assignment */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { downloadOriginalSchema, createSdkSchema } from './schema-separation-core.js';
import type { OpenAPI3 } from 'openapi-typescript';

// Mock global fetch
const mockFetch = vi.fn();
global.fetch = mockFetch;

describe('schema separation', () => {
  beforeEach(() => {
    process.env.OAK_API_KEY = 'test-api-key';
    vi.clearAllMocks();
  });

  afterEach(() => {
    delete process.env.OAK_API_KEY;
  });

  // shouldUseOriginalSchema removed: pipeline always decorates and consumes SDK schema

  describe('downloadOriginalSchema', () => {
    it('should download schema from API and save as api-schema-original.json', async () => {
      const mockSchema = {
        openapi: '3.0.3',
        info: { title: 'Oak OpenAPI' },
        components: {
          schemas: {
            LessonResponse: {
              type: 'object',
              properties: {
                title: { type: 'string' },
              },
            },
          },
        },
      };

      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve(mockSchema),
      });

      const result = await downloadOriginalSchema();

      expect(mockFetch).toHaveBeenCalledWith(
        'https://open-api.thenational.academy/api/v0/swagger.json',
        expect.objectContaining({
          headers: expect.any(Headers),
        }),
      );
      expect(result).toBeDefined();
      expect(result.openapi).toBe('3.0.3');
      expect(result.info.title).toBe('Oak OpenAPI');
    });
  });

  describe('createSdkSchema', () => {
    it('should create SDK schema with canonicalUrl fields from original schema', () => {
      const originalSchema: OpenAPI3 = {
        openapi: '3.0.3',
        info: { title: 'Oak OpenAPI', version: '1.0.0' },
        paths: {},
        components: {
          schemas: {
            LessonResponse: {
              type: 'object',
              properties: {
                title: { type: 'string' },
              },
            },
          },
        },
      };

      const sdkSchema = createSdkSchema(originalSchema);

      expect(sdkSchema.openapi).toBe('3.0.3');
      expect(sdkSchema.info.title).toBe('Oak OpenAPI');
      expect(sdkSchema.components?.schemas?.LessonResponse).toHaveProperty('properties');
      const lessonResponse = sdkSchema.components?.schemas?.LessonResponse as Record<
        string,
        unknown
      >;
      const properties = lessonResponse.properties as Record<string, unknown>;
      expect(properties).toHaveProperty('canonicalUrl');
      expect(properties.canonicalUrl).toHaveProperty('type', 'string');
    });

    it('should preserve all original schema fields while adding canonicalUrl', () => {
      const originalSchema: OpenAPI3 = {
        openapi: '3.0.3',
        info: { title: 'Oak OpenAPI', version: '1.0.0' },
        paths: {},
        components: {
          schemas: {
            LessonResponse: {
              type: 'object',
              properties: {
                title: { type: 'string' },
                description: { type: 'string' },
              },
            },
          },
        },
      };

      const sdkSchema = createSdkSchema(originalSchema);

      const lessonResponse = sdkSchema.components?.schemas?.LessonResponse as Record<
        string,
        unknown
      >;
      const properties = lessonResponse.properties as Record<string, unknown>;
      expect(properties.title).toEqual({ type: 'string' });
      expect(properties.description).toEqual({ type: 'string' });
      expect(properties.canonicalUrl).toEqual({
        type: 'string',
        description: 'The canonical URL for this resource, generated by the SDK',
        example: 'https://www.thenational.academy/teachers/lessons/example-lesson',
      });
    });
  });
});
