/**
 * Schema Decoration Core Functions
 *
 * Pure functions for decorating OpenAPI schemas with SDK-specific fields.
 * This module contains the core decoration logic that can be imported
 * by other scripts in the type generation pipeline.
 */

/* eslint-disable @typescript-eslint/consistent-type-assertions */
/* eslint-disable @typescript-eslint/no-restricted-types */
/* eslint-disable @typescript-eslint/no-redundant-type-constituents */
/* eslint-disable no-restricted-properties */

import type { OpenAPI3, SchemaObject } from 'openapi-typescript';

/**
 * Decorates a response schema with canonicalUrl field
 * @param schema - The response schema object
 * @returns Decorated schema with canonicalUrl field added
 */
export function decorateResponseSchema(schema: SchemaObject | unknown): SchemaObject | unknown {
  if (typeof schema !== 'object' || schema === null) {
    return schema;
  }

  const schemaObj = schema as Record<string, unknown>;

  // If it's a schema object with properties, add canonicalUrl
  if (isObjectSchema(schemaObj)) {
    return addCanonicalUrlToObjectSchema(schemaObj);
  }

  // If it's an array of schemas, decorate each item
  if (schemaObj.type === 'array' && schemaObj.items) {
    return {
      ...schemaObj,
      items: decorateResponseSchema(schemaObj.items),
    };
  }

  // If it's an anyOf/oneOf/allOf, decorate each option
  return decorateUnionSchema(schemaObj);
}

/**
 * Checks if a schema is an object schema with properties
 */
function isObjectSchema(schemaObj: Record<string, unknown>): boolean {
  return (
    schemaObj.type === 'object' &&
    Boolean(schemaObj.properties) &&
    typeof schemaObj.properties === 'object'
  );
}

/**
 * Adds canonicalUrl to an object schema
 */
function addCanonicalUrlToObjectSchema(
  schemaObj: Record<string, unknown>,
): Record<string, unknown> {
  const properties = schemaObj.properties as Record<string, unknown>;
  return {
    ...schemaObj,
    properties: {
      ...properties,
      canonicalUrl: {
        type: 'string',
        description: 'The canonical URL for this resource, generated by the SDK',
        example: 'https://www.thenational.academy/teachers/lessons/example-lesson',
      },
    },
  };
}

/**
 * Decorates union schemas (anyOf, oneOf, allOf)
 */
function decorateUnionSchema(schemaObj: Record<string, unknown>): Record<string, unknown> {
  if (Array.isArray(schemaObj.anyOf)) {
    return {
      ...schemaObj,
      anyOf: schemaObj.anyOf.map(decorateResponseSchema),
    };
  }

  if (Array.isArray(schemaObj.oneOf)) {
    return {
      ...schemaObj,
      oneOf: schemaObj.oneOf.map(decorateResponseSchema),
    };
  }

  if (Array.isArray(schemaObj.allOf)) {
    return {
      ...schemaObj,
      allOf: schemaObj.allOf.map(decorateResponseSchema),
    };
  }

  return schemaObj;
}

/**
 * Decorates the entire OpenAPI schema by adding canonicalUrl to all response schemas
 * @param schema - The canonical OpenAPI schema
 * @returns Decorated schema with canonicalUrl fields added to response schemas
 */
export function decorateOpenAPISchema(schema: OpenAPI3): OpenAPI3 {
  const decorated = JSON.parse(JSON.stringify(schema)) as OpenAPI3;

  // Add canonicalUrl to all response schemas in components
  if (decorated.components?.schemas) {
    const schemaEntries = Object.entries(decorated.components.schemas);
    for (const [schemaName, schemaDef] of schemaEntries) {
      // Only decorate response schemas (those that end with "ResponseSchema" or similar patterns)
      if (schemaName.includes('Response') || schemaName.includes('Schema')) {
        decorated.components.schemas[schemaName] = decorateResponseSchema(
          schemaDef,
        ) as SchemaObject;
      }
    }
  }

  return decorated;
}
