// Aggregated search, query parser, observability, and admin exports.

export {
  DEFAULT_INCLUDE_FACETS,
  SearchStructuredRequestSchema,
  isSearchStructuredRequest,
  SearchNaturalLanguageRequestSchema,
  isSearchNaturalLanguageRequest,
  SearchParsedQuerySchema,
  isSearchParsedQuery,
  SEARCH_SCOPES,
  SEARCH_SCOPES_WITH_ALL,
  isSearchScope,
  isSearchScopeWithAll,
  DEFAULT_SUGGESTION_CACHE,
  SearchSuggestionContextSchema,
  SearchSuggestionItemSchema,
  SearchSuggestionResponseSchema,
  SearchSuggestionRequestSchema,
  isSearchSuggestionRequest,
  isSearchSuggestionResponse,
  SearchLessonsResponseSchema,
  SearchUnitsResponseSchema,
  SearchSequencesResponseSchema,
  SearchMultiScopeResponseSchema,
  createSearchLessonsResponse,
  createSearchUnitsResponse,
  createSearchSequencesResponse,
  createSearchMultiScopeResponse,
  IndexMetaDocSchema,
  isIndexMetaDoc,
  ZeroHitDocSchema,
  isZeroHitDoc,
} from '../types/generated/search/index.js';

export {
  QueryParserRequestSchema,
  QueryParserResponseSchema,
  isQueryParserResponse,
  QUERY_PARSER_INTENT_ENUM,
} from '../types/generated/query-parser/index.js';
export type {
  QueryParserRequest,
  QueryParserResponse,
  QueryParserIntent,
} from '../types/generated/query-parser/index.js';

export {
  ZERO_HIT_SCOPES,
  ZeroHitScopeSchema,
  ZeroHitScopeBreakdownSchema,
  ZeroHitSummarySchema,
  ZeroHitEventSchema,
  ZeroHitTelemetrySchema,
  createZeroHitEvent,
  createZeroHitSummary,
  createZeroHitTelemetry,
  summariseZeroHitEvents,
  type ZeroHitScope,
  type ZeroHitScopeBreakdown,
  type ZeroHitSummary,
  type ZeroHitEvent,
  type ZeroHitTelemetry,
} from '../types/generated/observability/index.js';

export {
  ADMIN_STREAM_ACTIONS,
  AdminStreamActionSchema,
  AdminStreamSuccessSchema,
  AdminStreamErrorSchema,
  AdminStreamFixtureSchema,
  createAdminStreamFixture,
  createAdminStreamEmptyFixture,
  createAdminStreamErrorFixture,
  createAdminStreamFixtureMap,
  type AdminStreamAction,
  type AdminStreamSuccessFixture,
  type AdminStreamErrorFixture,
  type AdminStreamFixture,
  type AdminStreamFixtureMap,
} from '../types/generated/admin/index.js';

export type {
  SearchStructuredRequest,
  SearchStructuredScope,
  SearchNaturalLanguageRequest,
  SearchParsedQuery,
  SearchParsedIntent,
  SearchScope,
  SearchScopeWithAll,
  SearchSuggestionItem,
  SearchSuggestionResponse,
  SearchSuggestionRequest,
  SearchFacets,
  SequenceFacet,
  SequenceFacetUnit,
  SearchLessonsResponse,
  SearchUnitsResponse,
  SearchSequencesResponse,
  SearchLessonsSuggestions,
  SearchLessonsSuggestionCache,
  SearchLessonResult,
  SearchUnitResult,
  SearchSequenceResult,
  SearchMultiScopeBucket,
  SearchMultiScopeResponse,
  SearchLessonsIndexDoc,
  SearchUnitsIndexDoc,
  SearchUnitRollupDoc,
  SearchSequenceFacetsIndexDoc,
  SearchSequenceIndexDoc,
  SearchThreadIndexDoc,
  IndexMetaDoc,
  ZeroHitDoc,
  SearchSubjectSlug,
} from '../types/generated/search/index.js';

export {
  lessonSummarySchema,
  unitSummarySchema,
  subjectSequencesSchema,
  isUnitsGrouped,
  isLessonGroups,
  isTranscriptResponse,
  isLessonSummary,
  isUnitSummary,
  isSubjectSequences,
  type LessonSummaryResponseSchema,
  type UnitSummaryResponseSchema,
  type SubjectSequenceResponseSchema,
  type SearchLessonSummary,
  type SearchUnitSummary,
  type SearchSubjectSequences,
  sequenceUnitsSchema,
  type SequenceUnitsResponseSchema,
  type SequenceUnitsResponse,
  isSequenceUnitsResponse,
  subjectAssetsSchema,
  type SubjectAssetsResponseSchema,
  type SubjectAssets,
  isSubjectAssets,
} from '../types/search-response-guards.js';

export {
  SequenceFacetUnitSchema,
  SequenceFacetSchema,
  SearchFacetsSchema,
} from '../types/generated/zod/search/output/index.js';

export {
  SearchLessonsIndexDocSchema,
  SearchUnitsIndexDocSchema,
  SearchUnitRollupDocSchema,
  SearchSequenceIndexDocSchema,
  SearchSequenceFacetsIndexDocSchema,
  SearchThreadIndexDocSchema,
  isSearchLessonsIndexDoc,
  isSearchUnitsIndexDoc,
  isSearchUnitRollupDoc,
  isSearchSequenceIndexDoc,
  isSearchSequenceFacetsIndexDoc,
  isSearchThreadIndexDoc,
} from '../types/generated/search/index.js';
