/**
 * Integration test: verifies the sdk-codegen → search-sdk contract
 * through the createSearchRetrieval convenience factory.
 *
 * Uses a real ES Client with mocked transport to avoid network calls.
 * This proves that types generated by sdk-codegen compose correctly
 * through createSearchRetrieval → createSearchSdk → retrieval pipeline.
 */

import { describe, it, expect, vi } from 'vitest';
import { Client } from '@elastic/elasticsearch';
import { createSearchRetrieval } from './create-search-retrieval.js';
import { createSearchSdk } from './create-search-sdk.js';

const EMPTY_SEARCH_RESPONSE = {
  hits: { total: { value: 0, relation: 'eq' as const }, max_score: null, hits: [] },
  took: 1,
  timed_out: false,
  _shards: { total: 1, successful: 1, failed: 0, skipped: 0 },
};

describe('createSearchRetrieval contract (sdk-codegen → search-sdk)', () => {
  const credentials = {
    ELASTICSEARCH_URL: 'https://fake-es:9200',
    ELASTICSEARCH_API_KEY: 'fake-key',
  };

  function createMockedRetrieval() {
    const esClient = new Client({ node: credentials.ELASTICSEARCH_URL });
    vi.spyOn(esClient, 'search').mockResolvedValue(EMPTY_SEARCH_RESPONSE);

    return createSearchRetrieval(credentials, {
      createEsClient: () => esClient,
      createSdk: (config) => createSearchSdk(config),
    });
  }

  it('creates a retrieval service with all expected methods', () => {
    const retrieval = createMockedRetrieval();

    expect(typeof retrieval.searchLessons).toBe('function');
    expect(typeof retrieval.searchUnits).toBe('function');
    expect(typeof retrieval.searchSequences).toBe('function');
    expect(typeof retrieval.searchThreads).toBe('function');
    expect(typeof retrieval.suggest).toBe('function');
    expect(typeof retrieval.fetchSequenceFacets).toBe('function');
  });

  it('searchLessons returns ok Result with correct structure for empty results', async () => {
    const retrieval = createMockedRetrieval();
    const result = await retrieval.searchLessons({ text: 'test query' });

    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.value.scope).toBe('lessons');
      expect(result.value.results).toStrictEqual([]);
      expect(typeof result.value.took).toBe('number');
      expect(typeof result.value.timedOut).toBe('boolean');
      expect(typeof result.value.total).toBe('number');
    }
  });
});
