/* eslint-disable max-lines -- generator with serialisation requires length */
/* eslint-disable max-lines-per-function -- serialisation functions are long by nature */
/**
 * Misconception graph generator for the vocabulary mining pipeline.
 *
 * @remarks
 * Generates a graph of misconceptions extracted from curriculum lessons.
 * This graph helps teachers identify common mistakes and AI agents provide
 * targeted tutoring support.
 *
 * @module vocab-gen/generators/misconception-graph-generator
 */
import { writeFile } from 'fs/promises';
import { join } from 'path';

import type { ExtractedMisconception } from '../extractors/index.js';

/**
 * A misconception node in the graph.
 */
export interface MisconceptionNode {
  /** The incorrect belief or common mistake */
  readonly misconception: string;
  /** How to address or correct the misconception */
  readonly response: string;
  /** Subject where this misconception appears */
  readonly subject: string;
  /** Key stage where this misconception is addressed */
  readonly keyStage: string;
  /** Lesson that addresses this misconception */
  readonly lessonSlug: string;
  /** Lesson title for context */
  readonly lessonTitle: string;
}

/**
 * Statistics about the misconception graph.
 */
export interface MisconceptionGraphStats {
  /** Total number of misconceptions */
  readonly totalMisconceptions: number;
  /** Count of misconceptions by subject */
  readonly bySubject: Readonly<Record<string, number>>;
  /** Count of misconceptions by key stage */
  readonly byKeyStage: Readonly<Record<string, number>>;
  /** List of subjects covered */
  readonly subjectsCovered: readonly string[];
}

/**
 * The complete misconception graph structure.
 */
export interface MisconceptionGraph {
  /** Semantic version of this graph */
  readonly version: string;
  /** When this graph was generated */
  readonly generatedAt: string;
  /** Source data version */
  readonly sourceVersion: string;
  /** Statistics about the graph */
  readonly stats: MisconceptionGraphStats;
  /** All misconception nodes */
  readonly nodes: readonly MisconceptionNode[];
  /** Cross-reference to related resources */
  readonly seeAlso: string;
}

/**
 * Calculates statistics from misconceptions.
 */
function calculateStats(
  misconceptions: readonly ExtractedMisconception[],
): MisconceptionGraphStats {
  const bySubject: Record<string, number> = {};
  const byKeyStage: Record<string, number> = {};
  const subjects = new Set<string>();

  for (const m of misconceptions) {
    bySubject[m.subject] = (bySubject[m.subject] ?? 0) + 1;
    byKeyStage[m.keyStage] = (byKeyStage[m.keyStage] ?? 0) + 1;
    subjects.add(m.subject);
  }

  return {
    totalMisconceptions: misconceptions.length,
    bySubject,
    byKeyStage,
    subjectsCovered: [...subjects].sort(),
  };
}

/**
 * Converts extracted misconceptions to graph nodes.
 */
function toNodes(misconceptions: readonly ExtractedMisconception[]): readonly MisconceptionNode[] {
  return misconceptions.map((m) => ({
    misconception: m.misconception,
    response: m.response,
    subject: m.subject,
    keyStage: m.keyStage,
    lessonSlug: m.lessonSlug,
    lessonTitle: m.lessonTitle,
  }));
}

/**
 * Generates misconception graph data from extracted misconceptions.
 *
 * @param misconceptions - Array of extracted misconceptions
 * @param sourceVersion - Version of the source bulk data
 * @returns MisconceptionGraph with all misconceptions and statistics
 *
 * @example
 * ```ts
 * const graph = generateMisconceptionGraphData(extractedData.misconceptions, '2025-12-26');
 * console.log(`Found ${graph.stats.totalMisconceptions} misconceptions`);
 * ```
 */
export function generateMisconceptionGraphData(
  misconceptions: readonly ExtractedMisconception[],
  sourceVersion: string,
): MisconceptionGraph {
  return {
    version: '1.0.0',
    generatedAt: new Date().toISOString(),
    sourceVersion,
    stats: calculateStats(misconceptions),
    nodes: toNodes(misconceptions),
    seeAlso: 'Use get-ontology for curriculum structure context',
  };
}

/**
 * Escapes a string for use in TypeScript string literals.
 */
function escapeString(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r');
}

/**
 * Serializes a MisconceptionGraph to TypeScript source code.
 *
 * @param graph - The graph data to serialize
 * @returns TypeScript source code string
 */
export function serializeMisconceptionGraph(graph: MisconceptionGraph): string {
  const lines: string[] = [
    '/* eslint-disable max-lines -- generated static data file */',
    '/**',
    ' * Misconception Graph — extracted from bulk download data.',
    ' *',
    ' * @remarks',
    ' * - Generated by `pnpm vocab-gen`',
    ` * - Source: ${graph.sourceVersion}`,
    ` * - Generated: ${graph.generatedAt}`,
    ' * - Contains common misconceptions and how to address them',
    ' * - Use for teacher guidance and AI tutoring support',
    ' *',
    ' * @see ADR-086 for extraction methodology',
    ' */',
    '',
    '/**',
    ' * A misconception node in the graph.',
    ' */',
    'export interface MisconceptionNode {',
    '  readonly misconception: string;',
    '  readonly response: string;',
    '  readonly subject: string;',
    '  readonly keyStage: string;',
    '  readonly lessonSlug: string;',
    '  readonly lessonTitle: string;',
    '}',
    '',
    '/**',
    ' * Statistics about the misconception graph.',
    ' */',
    'export interface MisconceptionGraphStats {',
    '  readonly totalMisconceptions: number;',
    '  readonly bySubject: Readonly<Record<string, number>>;',
    '  readonly byKeyStage: Readonly<Record<string, number>>;',
    '  readonly subjectsCovered: readonly string[];',
    '}',
    '',
    '/**',
    ' * The complete misconception graph structure.',
    ' */',
    'export interface MisconceptionGraph {',
    '  readonly version: string;',
    '  readonly generatedAt: string;',
    '  readonly sourceVersion: string;',
    '  readonly stats: MisconceptionGraphStats;',
    '  readonly nodes: readonly MisconceptionNode[];',
    '  readonly seeAlso: string;',
    '}',
    '',
    '/**',
    ' * Misconception graph with common mistakes and teacher responses.',
    ' *',
    ' * @remarks',
    ` * Contains ${graph.stats.totalMisconceptions} misconceptions across ${graph.stats.subjectsCovered.length} subjects.`,
    ' *',
    ' * Use this to answer questions like:',
    ' * - "What mistakes should I watch for when teaching fractions?"',
    ' * - "How do I address misconceptions about photosynthesis?"',
    ' * - "What are common mistakes in this subject?"',
    ' */',
    'export const misconceptionGraph: MisconceptionGraph = {',
    `  version: '${graph.version}',`,
    `  generatedAt: '${graph.generatedAt}',`,
    `  sourceVersion: '${graph.sourceVersion}',`,
    '',
    '  stats: {',
    `    totalMisconceptions: ${graph.stats.totalMisconceptions},`,
    `    bySubject: ${JSON.stringify(graph.stats.bySubject)},`,
    `    byKeyStage: ${JSON.stringify(graph.stats.byKeyStage)},`,
    `    subjectsCovered: ${JSON.stringify(graph.stats.subjectsCovered)},`,
    '  },',
    '',
    '  nodes: [',
  ];

  // Add nodes
  for (const node of graph.nodes) {
    lines.push('    {');
    lines.push(`      misconception: '${escapeString(node.misconception)}',`);
    lines.push(`      response: '${escapeString(node.response)}',`);
    lines.push(`      subject: '${node.subject}',`);
    lines.push(`      keyStage: '${node.keyStage}',`);
    lines.push(`      lessonSlug: '${node.lessonSlug}',`);
    lines.push(`      lessonTitle: '${escapeString(node.lessonTitle)}',`);
    lines.push('    },');
  }

  lines.push('  ],');
  lines.push('');
  lines.push(`  seeAlso: '${escapeString(graph.seeAlso)}',`);
  lines.push('};');
  lines.push('');

  return lines.join('\n');
}

/**
 * Writes a misconception graph to a TypeScript file.
 *
 * @param graph - The graph data to write
 * @param outputDir - Directory to write the file to
 * @returns Path to the written file
 */
export async function writeMisconceptionGraphFile(
  graph: MisconceptionGraph,
  outputDir: string,
): Promise<string> {
  const fileName = 'misconception-graph-data.ts';
  const filePath = join(outputDir, fileName);
  const content = serializeMisconceptionGraph(graph);

  await writeFile(filePath, content, 'utf-8');

  return filePath;
}
