#!/usr/bin/env node

/**
 * Unified type generation pipeline
 *
 * Fetches OpenAPI schema and generates both TypeScript types and Zod validators
 */

import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execSync } from 'node:child_process';
import { fetchOpenAPISchema } from './schema-fetcher';
import { transformSchemaToTypeScript } from './typegen-typescript';
import { transformSchemaToZod } from './typegen-zod';

// Get directory paths for ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Configuration
const OAK_API_URL = 'https://oak-curriculum-api.vercel.app/api-docs/openapi.json';
const CACHE_PATH = resolve(__dirname, '../reference-types/api-schema.json');
const TYPES_OUTPUT = resolve(__dirname, '../src/types/generated.ts');
const VALIDATORS_OUTPUT = resolve(__dirname, '../src/validators/generated.ts');

/**
 * Generate TypeScript output with header
 */
function generateTypeScriptOutput(code: string): string {
  return `/**
 * GENERATED FILE - DO NOT EDIT
 * 
 * This file is automatically generated from the Oak Curriculum API OpenAPI schema.
 * To regenerate, run: pnpm generate:types
 * 
 * Last generated: ${new Date().toISOString()}
 */

${code}
`;
}

/**
 * Generate Zod output with header
 */
function generateZodOutput(code: string): string {
  return `/**
 * GENERATED FILE - DO NOT EDIT
 * 
 * This file contains Zod validators automatically generated from the Oak Curriculum API OpenAPI schema.
 * To regenerate, run: pnpm generate:types
 * 
 * Last generated: ${new Date().toISOString()}
 */

${code}
`;
}

/**
 * Main generation pipeline
 */
async function generateTypes(): Promise<void> {
  console.log('🔄 Fetching OpenAPI schema...');

  try {
    // Fetch schema with cache fallback
    const schema = await fetchOpenAPISchema(OAK_API_URL, CACHE_PATH);
    console.log('✅ Schema fetched successfully');

    // Generate TypeScript types
    console.log('🔨 Generating TypeScript types...');
    const typescriptCode = transformSchemaToTypeScript(schema);
    const typescriptOutput = generateTypeScriptOutput(typescriptCode);
    writeFileSync(TYPES_OUTPUT, typescriptOutput, 'utf-8');
    console.log(`✅ TypeScript types written to ${TYPES_OUTPUT}`);

    // Generate Zod validators
    console.log('🔨 Generating Zod validators...');
    const zodCode = transformSchemaToZod(schema);
    const zodOutput = generateZodOutput(zodCode);
    writeFileSync(VALIDATORS_OUTPUT, zodOutput, 'utf-8');
    console.log(`✅ Zod validators written to ${VALIDATORS_OUTPUT}`);

    // Format generated files with prettier
    console.log('💅 Formatting generated files...');
    execSync(`pnpm exec prettier --write ${TYPES_OUTPUT} ${VALIDATORS_OUTPUT}`, {
      cwd: resolve(__dirname, '..'),
      stdio: 'inherit',
    });

    console.log('🎉 Type generation complete!');
  } catch (error) {
    console.error('❌ Type generation failed:', error);
    process.exit(1);
  }
}

// Run if called directly
const isMainModule = import.meta.url === `file://${process.argv[1]}`;
if (isMainModule) {
  generateTypes().catch((error: unknown) => {
    console.error('Fatal error:', error);
    process.exit(1);
  });
}

export { generateTypes };
