#!/usr/bin/env node

/**
 * MCP Tool Generation Script
 *
 * This script runs AFTER zodgen and reads the actual generated Zod schemas
 * to create MCP tool validators. This maintains the central contract that
 * everything flows from the OpenAPI schema.
 *
 * Pipeline:
 * 1. typegen.ts - Generates OpenAPI artifacts and basic MCP tool types
 * 2. zodgen.ts - Generates Zod schemas from OpenAPI
 * 3. mcp-toolgen.ts (THIS FILE) - Reads Zod output and generates validators
 */

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Import the generated MCP tools
import { MCP_TOOLS_DATA } from '../src/types/generated/api-schema/mcp-tools.js';

const thisDirectory = path.dirname(fileURLToPath(import.meta.url));
const rootDirectory = path.resolve(thisDirectory, '..');

/**
 * Read the generated Zod endpoints file and extract schema names
 */
function readGeneratedSchemas(): Set<string> {
  const endpointsPath = path.join(rootDirectory, 'src/types/generated/zod/endpoints.ts');
  const content = readFileSync(endpointsPath, 'utf-8');

  // Find the schemas export
  const schemasMatch = /export const schemas = \{([^}]+)\}/s.exec(content);
  if (!schemasMatch) {
    throw new Error('Could not find schemas export in generated Zod file');
  }

  // Extract schema names
  const schemaNames = new Set<string>();
  const schemaLines = schemasMatch[1].split(',');
  for (const line of schemaLines) {
    const trimmed = line.trim();
    if (trimmed) {
      // Handle both "SchemaName," and "SchemaName: SchemaName," formats
      const match = /^(\w+)/.exec(trimmed);
      if (match) {
        schemaNames.add(match[1]);
      }
    }
  }

  return schemaNames;
}

/**
 * Map MCP tool to its corresponding Zod schema
 * This reads from actual generated schemas, not predictions
 */
function mapToolToSchema(_toolName: string, operationId: string, schemaNames: Set<string>): string {
  // Try to find a matching schema based on the operation ID
  // The zodgen creates schema names based on the response schemas in OpenAPI

  // Common patterns from observation:
  // - getSequences-getSequenceUnits -> SequenceUnitsResponseSchema
  // - getLessonTranscript-getLessonTranscript -> TranscriptResponseSchema
  // - searchTranscripts-searchTranscripts -> SearchTranscriptResponseSchema

  // Extract the main operation name
  const parts = operationId.split('-');
  const lastPart = parts[parts.length - 1];

  // Try different schema name patterns
  const candidates = [
    `${lastPart}ResponseSchema`,
    `${lastPart.replace(/^get/, '')}ResponseSchema`,
    `${lastPart.replace(/^search/, 'Search')}ResponseSchema`,
    `${lastPart.replace(/^get/, '').replace(/s$/, '')}ResponseSchema`,
  ];

  for (const candidate of candidates) {
    if (schemaNames.has(candidate)) {
      return candidate;
    }
  }

  // Special cases that don't follow patterns
  const specialCases: Record<string, string> = {
    'changelog-changelog':
      'z.array(z.object({ version: z.string(), date: z.string(), changes: z.array(z.string()) }).passthrough())',
    'changelog-latest':
      'z.object({ version: z.string(), date: z.string(), changes: z.array(z.string()) }).passthrough()',
    'getSubjects-getSubjectYears': 'z.array(z.number())',
  };

  if (specialCases[operationId]) {
    return specialCases[operationId];
  }

  // Default to unknown
  return 'z.unknown()';
}

/**
 * Generate the MCP validator mapping file
 */
function generateValidatorMapping(): string {
  const schemaNames = readGeneratedSchemas();
  console.log(`Found ${String(schemaNames.size)} schemas in generated Zod file`);

  const lines: string[] = [
    '/**',
    ' * MCP Tool Validator Mapping',
    ' * Generated from actual Zod schemas - DO NOT EDIT MANUALLY',
    ' * ',
    ' * This file is generated AFTER zodgen runs, reading the actual',
    ' * generated schemas to maintain the central contract.',
    ' */',
    '',
    "import { z } from 'zod';",
    "import type { McpToolName } from './mcp-tools.js';",
    "import { schemas } from '../zod/endpoints.js';",
    '',
    '/**',
    ' * Map of MCP tool names to their Zod validators',
    ' * Generated by reading actual Zod output',
    ' */',
    'export const MCP_TOOL_VALIDATORS = {',
  ];

  // Generate mapping for each tool
  for (const [toolName, toolData] of Object.entries(MCP_TOOLS_DATA)) {
    const schemaName = mapToolToSchema(toolName, toolData.operationId, schemaNames);

    if (schemaName.startsWith('z.')) {
      // Inline Zod schema
      lines.push(`  '${toolName}': ${schemaName},`);
    } else if (schemaName !== 'z.unknown()') {
      // Reference to schemas object
      lines.push(`  '${toolName}': schemas.${schemaName},`);
    } else {
      // Unknown schema
      lines.push(`  '${toolName}': z.unknown(),`);
    }
  }

  lines.push('} as const;');
  lines.push('');

  // Add helper types and functions
  lines.push(
    '/**',
    ' * Helper type to extract the validated response type for a tool',
    ' */',
    'export type GetToolValidatedResponse<T extends McpToolName> =',
    '  T extends keyof typeof MCP_TOOL_VALIDATORS',
    '    ? z.infer<typeof MCP_TOOL_VALIDATORS[T]>',
    '    : unknown;',
    '',
    '/**',
    ' * Validate a response for a specific tool',
    ' * @param toolName - The MCP tool name',
    ' * @param response - The response to validate',
    ' * @returns The validated response',
    ' * @throws ZodError if validation fails',
    ' */',
    'export function validateToolResponse<T extends McpToolName>(',
    '  toolName: T,',
    '  response: unknown',
    '): GetToolValidatedResponse<T> {',
    '  const validator = MCP_TOOL_VALIDATORS[toolName];',
    '  if (!validator) {',
    '    throw new Error(`No validator found for tool: ${toolName}`);',
    '  }',
    '  return validator.parse(response);',
    '}',
    '',
  );

  return lines.join('\n');
}

void (() => {
  console.log('🔨 Generating MCP validator mappings from actual Zod schemas...');

  try {
    const validatorContent = generateValidatorMapping();

    // Write the validator mapping file
    const outputPath = path.join(rootDirectory, 'src/types/generated/api-schema/mcp-validators.ts');
    writeFileSync(outputPath, validatorContent, 'utf-8');

    console.log('✅ MCP validator generation complete!');
  } catch (error) {
    console.error('❌ MCP validator generation failed:', error);
    process.exit(1);
  }
})().catch((error: unknown) => {
  console.error('❌ Unexpected error:', error);
  process.exit(1);
});
