#!/usr/bin/env sh

# Check for breaking changes first, we want to block accidental major version bumps
pnpm agent-tools:prevent-accidental-major-version "$1" || exit 1

# Then run commitlint
pnpm dlx commitlint --edit $1
