/**
 * Operation code generators
 * Generates TypeScript code strings for path operations
 */

import type { ExtractedOperation } from './operation-extraction.js';

/**
 * Generate TypeScript code for PATH_OPERATIONS constant
 */
export function generatePathOperationsConstant(operations: ExtractedOperation[]): string {
  const operationsJson = JSON.stringify(operations, null, 2);

  return `
/**
 * All path operations extracted from the OpenAPI schema
 * Generated at build time for runtime use
 */
export const PATH_OPERATIONS = ${operationsJson} as const;

export type PathOperation = (typeof PATH_OPERATIONS)[number];
`;
}

/**
 * Generate TypeScript code for OPERATIONS_BY_ID map
 */
export function generateOperationsByIdConstant(operations: ExtractedOperation[]): string {
  const operationsWithId = operations.filter((op) => op.operationId);

  if (operationsWithId.length === 0) {
    return `
/**
 * Map of operations by their operationId
 * Generated at build time for runtime use
 */
export const OPERATIONS_BY_ID = {} as const;

export type OperationId = never;
`;
  }

  const entries = operationsWithId
    .map((op) => {
      const originalIndex = operations.indexOf(op);
      return `  "${op.operationId ?? ''}": PATH_OPERATIONS[${String(originalIndex)}]`;
    })
    .join(',\n');

  return `
/**
 * Map of operations by their operationId
 * Generated at build time for runtime use
 */
export const OPERATIONS_BY_ID = {
${entries}
} as const;

export type OperationIdToOperationMap = typeof OPERATIONS_BY_ID;
export type OperationId = keyof OperationIdToOperationMap;
export function isOperationId(value: string): value is OperationId { return value in OPERATIONS_BY_ID; }
`;
}

/**
 * Generate TypeScript code for ALLOWED_METHODS constant
 * Note: This doesn't generate isAllowedMethod as it's already generated
 * by the runtime schema checks
 */
export function generateAllowedMethodsConstant(methods: string[]): string {
  const methodsJson = JSON.stringify(methods, null, 2);

  return `
/**
 * All HTTP methods used in the API (from PATH_OPERATIONS)
 * Generated at build time for runtime use
 */
export const ALLOWED_METHODS = ${methodsJson} as const;
`;
}

/**
 * Generate all operation-related constants
 */
export function generateOperationConstants(operations: ExtractedOperation[]): string {
  const sections = [
    generatePathOperationsConstant(operations),
    generateOperationsByIdConstant(operations),
    // Note: We don't generate ALLOWED_METHODS here as allowedMethods is already
    // generated by the runtime schema checks in generateRuntimeSchemaChecks()
  ];

  return sections.join('\n');
}
