/**
 * Schema Decoration Core Functions
 *
 * Pure functions for decorating OpenAPI schemas with SDK-specific fields.
 * This module contains the core decoration logic that can be imported
 * by other scripts in the type generation pipeline.
 */

import type { OpenAPIObject, SchemaObject, ReferenceObject } from 'openapi3-ts/oas31';

function isOpenAPIObject(value: unknown): value is OpenAPIObject {
  return (
    typeof value === 'object' &&
    value !== null &&
    'openapi' in value &&
    'info' in value &&
    'paths' in value
  );
}

/**
 * Decorates a response schema with canonicalUrl field
 * @param schema - The response schema object
 * @returns Decorated schema with canonicalUrl field added
 */
export function decorateResponseSchema(
  schemaObj: SchemaObject | ReferenceObject,
): SchemaObject | ReferenceObject {
  // Handle ReferenceObject
  if ('$ref' in schemaObj) {
    return schemaObj;
  }

  // Now we know it's SchemaObject
  if (schemaObj.properties) {
    return addCanonicalUrlToObjectSchema(schemaObj);
  }

  if (schemaObj.type === 'array' && schemaObj.items) {
    return {
      ...schemaObj,
      items: decorateResponseSchema(schemaObj.items),
    };
  }

  // If it's an anyOf/oneOf/allOf, decorate each option
  return decorateUnionSchema(schemaObj);
}

/**
 * Adds canonicalUrl to an object schema
 */
function addCanonicalUrlToObjectSchema(schemaObj: SchemaObject): SchemaObject {
  const properties = schemaObj.properties;
  return {
    ...schemaObj,
    properties: {
      ...properties,
      canonicalUrl: {
        type: 'string',
        description: 'The canonical URL for this resource, generated by the SDK',
        example: 'https://www.thenational.academy/teachers/lessons/example-lesson',
      },
    },
  };
}

/**
 * Decorates union schemas (anyOf, oneOf, allOf)
 */
function decorateUnionSchema(schemaObj: SchemaObject): SchemaObject {
  if (schemaObj.anyOf && schemaObj.anyOf.length > 0) {
    return {
      ...schemaObj,
      anyOf: schemaObj.anyOf.map(decorateResponseSchema),
    };
  }

  if (schemaObj.oneOf && schemaObj.oneOf.length > 0) {
    return {
      ...schemaObj,
      oneOf: schemaObj.oneOf.map(decorateResponseSchema),
    };
  }

  if (schemaObj.allOf && schemaObj.allOf.length > 0) {
    return {
      ...schemaObj,
      allOf: schemaObj.allOf.map(decorateResponseSchema),
    };
  }

  return schemaObj;
}

/**
 * Decorates the entire OpenAPI schema by adding canonicalUrl to all response schemas
 * @param schema - The canonical OpenAPI schema
 * @returns Decorated schema with canonicalUrl fields added to response schemas
 */
export function decorateOpenAPISchema(schema: OpenAPIObject): OpenAPIObject {
  // Clone using structuredClone for proper deep copy
  const cloned: unknown = structuredClone(schema);

  if (!isOpenAPIObject(cloned)) {
    throw new TypeError('Failed to clone OpenAPI schema');
  }

  // Now cloned is properly typed as OpenAPIObject
  const decorated: OpenAPIObject = cloned;

  if (!decorated.components?.schemas) {
    return decorated;
  }

  // Iterate type-safely over schemas
  const schemas = decorated.components.schemas;
  for (const schemaName in schemas) {
    if (Object.hasOwn(schemas, schemaName)) {
      const schemaDef = schemas[schemaName];
      // Only decorate response schemas (those that end with "ResponseSchema" or similar patterns)
      if (schemaName.includes('Response') || schemaName.includes('Schema')) {
        schemas[schemaName] = decorateResponseSchema(schemaDef);
      }
    }
  }

  return decorated;
}
