import type { ParamMetadataMap } from './param-metadata.js';
import { buildZodFields } from './build-zod-type.js';
import { jsonSchemaFromPrimitive } from './build-json-schema-property.js';

export type {
  JsonSchemaProperty,
  JsonSchemaPropertyString,
  JsonSchemaPropertyNumber,
  JsonSchemaPropertyBoolean,
  JsonSchemaPropertyArray,
  JsonSchemaObject,
} from './json-schema-types.js';

import type { JsonSchemaObject, JsonSchemaProperty } from './json-schema-types.js';

/**
 * Build a flat JSON Schema object for MCP tool parameters from path/query metadata.
 *
 * Merges path and query parameters into a single flat object structure
 * that matches how MCP clients send arguments. This aligns with the
 * flat Zod schema generated by buildFlatMcpZodObject().
 *
 * Pure, compile-time friendly, no type assertions at call sites.
 *
 * @param pathParams - Path parameter metadata from OpenAPI
 * @param queryParams - Query parameter metadata from OpenAPI
 * @returns Flat JSON Schema object with all parameters at top level
 *
 * @example
 * ```typescript
 * // Input: path: { lesson: 'abc' }, query: { q: 'search' }
 * // Output: { type: 'object', properties: { lesson: {...}, q: {...} }, ... }
 * ```
 *
 * @remarks
 * - Parameters appear at top level (no params/path/query nesting)
 * - Path parameters listed before query parameters for consistency
 * - Mirrors buildFlatMcpZodObject() structure for JSON Schema
 * - MCP protocol expects flat arguments: { lesson: 'x' } not { params: { path: { lesson: 'x' } } }
 *
 * @see buildFlatMcpZodObject - Generates equivalent flat Zod schema
 * @see .agent/plans/fix-e2e-test-isolation.md (Phase 3B)
 */
export function buildInputSchemaObject(
  pathParams: ParamMetadataMap,
  queryParams: ParamMetadataMap,
): JsonSchemaObject {
  // Merge path and query parameters - path first for consistency with buildFlatMcpZodObject
  const allEntries = [...Object.entries(pathParams), ...Object.entries(queryParams)];

  const properties: Record<string, JsonSchemaProperty> = {};
  const required: string[] = [];

  for (const [name, meta] of allEntries) {
    properties[name] = jsonSchemaFromPrimitive(meta);
    if (meta.required) {
      required.push(name);
    }
  }

  return {
    type: 'object',
    properties,
    additionalProperties: false,
    ...(required.length > 0 ? { required } : {}),
  };
}

export function buildZodObject(
  pathParams: ParamMetadataMap,
  queryParams: ParamMetadataMap,
): string {
  const pathEntries = Object.entries(pathParams);
  const queryEntries = Object.entries(queryParams);
  const hasPath = pathEntries.length > 0;
  const hasQuery = queryEntries.length > 0;

  if (!hasPath && !hasQuery) {
    return 'z.object({ params: z.object({}) })';
  }

  const paramsShape: string[] = [];

  if (hasPath) {
    const fields = buildZodFields(pathEntries).join(', ');
    paramsShape.push(`path: z.object({ ${fields} })`);
  }

  if (hasQuery) {
    const fields = buildZodFields(queryEntries).join(', ');
    const maybeOptional = queryEntries.some(([, meta]) => meta.required) ? '' : '.optional()';
    paramsShape.push(`query: z.object({ ${fields} })${maybeOptional}`);
  }

  const paramsSchema =
    paramsShape.length > 0 ? `z.object({ ${paramsShape.join(', ')} })` : 'z.object({})';

  return `z.object({ params: ${paramsSchema} })`;
}

/**
 * Build a flat Zod object for MCP tool registration.
 *
 * Merges path and query parameters into a single flat object structure
 * that MCP clients can navigate to discover individual parameters.
 *
 * This differs from buildZodObject which creates nested structure
 * (params → path/query) for internal SDK type safety.
 *
 * @param pathParams - Path parameter metadata from OpenAPI
 * @param queryParams - Query parameter metadata from OpenAPI
 * @returns Zod schema string with flat parameter structure
 *
 * @example
 * ```typescript
 * // Input: path: { id: 'ks1' }, query: { q: 'search' }
 * // Output: "z.object({ id: z.string(), q: z.string() })"
 * ```
 *
 * @remarks
 * - Reuses existing buildZodFields() for type generation
 * - Parameters appear at top level (no params/path/query nesting)
 * - Path parameters listed before query parameters
 * - MCP clients can discover and document each parameter individually
 *
 * @see buildZodObject - Generates nested structure for SDK internal use
 * @see .agent/plans/p0-mcp-flat-schema-generator-fix.md
 * @see .agent/research/deep-reflection-schema-first-and-findings.md (Priority 0)
 */
export function buildFlatMcpZodObject(
  pathParams: ParamMetadataMap,
  queryParams: ParamMetadataMap,
): string {
  // Merge path and query parameters - path first for consistency
  const allEntries = [...Object.entries(pathParams), ...Object.entries(queryParams)];

  // Handle zero-parameter tools
  if (allEntries.length === 0) {
    return 'z.object({})';
  }

  // Reuse existing buildZodFields which handles all type generation logic:
  // - Enum unions (z.literal values)
  // - Optional parameters (.optional())
  // - Array types
  // - Primitive types
  const fields = buildZodFields(allEntries).join(', ');

  return `z.object({ ${fields} })`;
}
